/*
 * Uebersetzungen fuer module.js und rezepte.js: Italienisch, Franzoesisch,
 * Spanisch. Deutsch und Englisch stehen direkt in den beiden Dateien.
 *
 * Schluessel ist der deutsche Text, wie ueberall in Anker. Aendert jemand
 * einen deutschen Satz in module.js oder rezepte.js, findet die App hier
 * nichts mehr und zeigt an dieser Stelle Englisch; werkzeug/pruefe-module.js
 * meldet genau das.
 *
 * Diese Uebersetzungen sind sorgfaeltig gemacht, aber nicht von
 * Muttersprachlerinnen und nicht von medizinischem Fachpersonal geprueft.
 */
window.ANKER_UEBERSETZUNG = {
 "it": {
  "Zoeliakie": "Celiachia",
  "Glutenfreie Ernaehrung ist die Behandlung. Die App fragt jeden Tag nach dem Essen und behaelt die Werte im Blick, die bei Zoeliakie kippen.": "La dieta senza glutine è la terapia. L'app chiede ogni giorno del cibo e tiene d'occhio i valori che nella celiachia tendono a scendere.",
  "Bauch": "Pancia",
  "ruhig": "tranquilla",
  "starke Beschwerden": "disturbi forti",
  "Der Tag beim Essen": "La giornata a tavola",
  "Alles sicher": "Tutto sicuro",
  "Etwas war unsicher": "Qualcosa era incerto",
  "Gluten bekommen": "Ho preso glutine",
  "Weizen, Roggen, Gerste, Dinkel und alles daraus": "Frumento, segale, orzo, farro e tutto ciò che ne deriva",
  "Schon kleine Mengen schaedigen die Duenndarmschleimhaut, auch ohne spuerbare Beschwerden.": "Anche piccole quantità danneggiano la mucosa dell'intestino tenue, con o senza sintomi.",
  "Hafer nur als glutenfrei gekennzeichnet": "Avena solo se etichettata senza glutine",
  "Normaler Hafer ist fast immer verunreinigt. Ein kleiner Teil der Betroffenen vertraegt auch reinen Hafer nicht; das zeigt der Verlauf, nicht ein Gefuehl.": "L'avena normale è quasi sempre contaminata. Una piccola parte delle persone reagisce anche all'avena pura; lo mostra l'andamento, non una sensazione.",
  "Sojasauce, Malz, Bruehen, Fertigsaucen": "Salsa di soia, malto, brodi, salse pronte",
  "Die haeufigsten versteckten Quellen. Das Zutatenverzeichnis jedes Mal lesen, Rezepturen aendern sich.": "Le fonti nascoste più comuni. Leggi ogni volta gli ingredienti, le ricette cambiano.",
  "Eisen, Kalzium, Vitamin D, Folsaeure, B12 im Blick": "Ferro, calcio, vitamina D, acido folico, B12 sotto controllo",
  "Bei Zoeliakie oft niedrig, besonders am Anfang. Messen lassen statt auf Verdacht ergaenzen.": "Spesso bassi nella celiachia, soprattutto all'inizio. Meglio farli misurare che integrare a caso.",
  "Brauche ich eine Ueberweisung zur Diaetologie?": "Ho bisogno di un'impegnativa per il dietologo?",
  "Systemischer Lupus (SLE)": "Lupus eritematoso sistemico (LES)",
  "Lupus": "Lupus",
  "Lupus zeigt sich ueberall ein wenig. Die App sammelt Gelenke, Haut, Kopf und Muedigkeit an einer Stelle, damit beim Termin das Muster sichtbar wird.": "Il lupus si fa sentire un po' ovunque. L'app raccoglie articolazioni, pelle, testa e stanchezza in un unico posto, così alla visita si vede lo schema.",
  "Gelenke": "Articolazioni",
  "frei": "libere",
  "steif, geschwollen": "rigide, gonfie",
  "Kopf klar": "Testa lucida",
  "klar": "lucida",
  "im Nebel": "nella nebbia",
  "Sonne und Licht": "Sole e luce",
  "Geschuetzt": "Protetta la pelle",
  "Etwas abbekommen": "Preso un po' di sole",
  "Viel abbekommen": "Preso molto sole",
  "Mediterranes Muster": "Un modello mediterraneo",
  "Gemuese, Huelsenfruechte, Olivenoel, Fisch. Es gibt Hinweise auf weniger Krankheitsaktivitaet und ein besseres Herzrisiko, aber keine Diaet, die Lupus heilt.": "Verdure, legumi, olio d'oliva, pesce. Ci sono segnali di minore attività di malattia e di un rischio cardiaco migliore, ma nessuna dieta guarisce il lupus.",
  "Alfalfa-Sprossen": "Germogli di erba medica",
  "Enthalten L-Canavanin, das in Berichten Lupus-aehnliche Schuebe ausgeloest hat. Die Belege sind alt und duenn, der Verzicht kostet nichts.": "Contengono L-canavanina, che in alcuni casi descritti ha scatenato riacutizzazioni simili al lupus. Le prove sono vecchie e scarse, rinunciarvi non costa nulla.",
  "Echinacea und andere Immun-Booster": "Echinacea e altri stimolanti del sistema immunitario",
  "Sollen das Immunsystem anregen, genau das ist bei Lupus nicht das Ziel. Vorher in der Sprechstunde fragen.": "Servono a stimolare il sistema immunitario, che nel lupus non è l'obiettivo. Chiedi prima in ambulatorio.",
  "Kalzium und Vitamin D bei Kortison": "Calcio e vitamina D con il cortisone",
  "Kortison kostet Knochen. Ob und wie viel ergaenzt wird, entscheidet die Aerztin nach Messung.": "Il cortisone indebolisce le ossa. Se e quanto integrare lo decide il medico dopo una misurazione.",
  "Wie aktiv ist mein Lupus gerade, in Zahlen?": "Quanto è attivo il mio lupus in questo momento, in numeri?",
  "Wann wurde zuletzt der Urin auf Eiweiss geprueft?": "Quando sono state controllate l'ultima volta le proteine nelle urine?",
  "Wann ist die naechste Netzhautkontrolle faellig?": "Quando è previsto il prossimo controllo della retina?",
  "Psoriasis": "Psoriasi",
  "Haut, Juckreiz und Gelenke. Gelenkbeschwerden bei Psoriasis gehoeren frueh angesprochen, weil eine Psoriasis-Arthritis behandelbar ist, bevor sie Schaden macht.": "Pelle, prurito e articolazioni. I dolori articolari con la psoriasi vanno segnalati presto, perché l'artrite psoriasica si può curare prima che faccia danni.",
  "Haut": "Pelle",
  "stark befallen": "molto estesa",
  "Juckreiz": "Prurito",
  "keiner": "nessuno",
  "quaelend": "insopportabile",
  "Haut gepflegt und behandelt": "Pelle curata e trattata",
  "Wie geplant": "Come previsto",
  "Teilweise": "In parte",
  "Heute nicht": "Oggi no",
  "neue Plaques": "nuove placche",
  "Kopfhaut": "cuoio capelluto",
  "Naegel": "unghie",
  "Hautrisse": "pelle screpolata",
  "geschwollener Finger oder Zeh": "dito della mano o del piede gonfio",
  "Infekt, Halsweh": "infezione, mal di gola",
  "Gewicht und mediterranes Muster": "Peso e modello mediterraneo",
  "Bei Uebergewicht bessert Abnehmen die Haut in Studien messbar und laesst Medikamente besser wirken.": "In caso di sovrappeso, perdere qualche chilo migliora la pelle in modo misurabile negli studi e aiuta la terapia a funzionare meglio.",
  "Alkohol": "Alcol",
  "Haengt mit schwereren Verlaeufen zusammen und vertraegt sich mit einigen Medikamenten schlecht, etwa Methotrexat.": "Associato a decorsi più gravi e poco compatibile con alcuni farmaci, come il metotrexato.",
  "Glutenfrei nur mit Grund": "Senza glutine solo con un motivo",
  "Hilft in Studien nur, wenn Zoeliakie-Antikoerper nachweisbar sind. Dann aber deutlich. Testen lassen statt raten.": "Negli studi aiuta solo se sono presenti anticorpi della celiachia. In quel caso aiuta chiaramente. Fai il test, non indovinare.",
  "Koennten meine Gelenkbeschwerden eine Psoriasis-Arthritis sein?": "I miei dolori articolari potrebbero essere un'artrite psoriasica?",
  "Wie gross ist der befallene Hautanteil, und ist eine systemische Behandlung sinnvoll?": "Quanta pelle è interessata, e avrebbe senso una terapia sistemica?",
  "Sollen Blutdruck, Blutfette und Blutzucker kontrolliert werden?": "Vanno controllati pressione, grassi nel sangue e glicemia?",
  "Hashimoto-Thyreoiditis": "Tiroidite di Hashimoto",
  "Hashimoto": "Hashimoto",
  "Viel haengt an einer Tablette zur richtigen Zeit und an einem Wert. Die App fragt nach dem einen und behaelt den anderen im Verlauf.": "Molto dipende da una compressa presa al momento giusto e da un valore. L'app chiede della prima e segue il secondo nel tempo.",
  "Kaelteempfinden": "Sensazione di freddo",
  "normal": "normale",
  "staendig kalt": "sempre freddo",
  "Schilddruesentablette": "Compressa per la tiroide",
  "Nuechtern genommen": "Presa a digiuno",
  "Mit Essen oder Kaffee": "Con cibo o caffè",
  "Vergessen": "Dimenticata",
  "kaelteempfindlich": "sensibile al freddo",
  "Gewicht steigt": "peso in aumento",
  "trockene Haut": "pelle secca",
  "Stimmung gedrueckt": "umore giù",
  "fT4": "fT4",
  "Schilddruese": "Tiroide",
  "Das freie Schilddruesenhormon. Zusammen mit dem TSH sagt es, ob die Dosis passt. Blut am besten vor der Tabletteneinnahme abnehmen lassen.": "L'ormone tiroideo libero. Insieme al TSH mostra se la dose è giusta. Meglio fare il prelievo prima della compressa.",
  "TPO-Antikoerper": "Anticorpi anti-TPO",
  "Bestaetigen die Autoimmunerkrankung. Ihre Hoehe steuert nicht die Behandlung und muss nicht laufend gemessen werden.": "Confermano la malattia autoimmune. Il loro livello non guida la terapia e non va misurato regolarmente.",
  "Tablette nuechtern, mit Wasser": "Compressa a digiuno, con acqua",
  "30 bis 60 Minuten vor dem Fruehstueck, immer gleich. Kaffee, Soja und Ballaststoffe dazwischen verringern die Aufnahme.": "Da 30 a 60 minuti prima della colazione, sempre allo stesso modo. Caffè, soia e fibre nel frattempo ne riducono l'assorbimento.",
  "Kalzium, Eisen und Magnesium mit Abstand": "Calcio, ferro e magnesio a distanza",
  "Mindestens vier Stunden Abstand zur Tablette, sonst wird weniger Hormon aufgenommen.": "Almeno quattro ore di distanza dalla compressa, altrimenti si assorbe meno ormone.",
  "Jod und Selen nicht auf eigene Faust": "Iodio e selenio non di propria iniziativa",
  "Normale Ernaehrung mit Jodsalz reicht. Hoch dosierte Praeparate koennen schaden, der Nutzen von Selen ist nicht gesichert.": "Un'alimentazione normale con sale iodato basta. I prodotti ad alto dosaggio possono nuocere, il beneficio del selenio non è dimostrato.",
  "Passt meine Dosis zum letzten TSH-Wert, und wann wird wieder kontrolliert?": "La mia dose va bene per l'ultimo TSH, e quando è il prossimo controllo?",
  "Muss ich den Abstand zu anderen Medikamenten oder Ergaenzungen aendern?": "Devo cambiare la distanza da altri farmaci o integratori?",
  "Rheumatoide Arthritis": "Artrite reumatoide",
  "Arthritis": "Artrite",
  "Welche Gelenke, wie lange steif am Morgen, wie geschwollen. Genau das fragt die Rheumatologie, und genau das vergisst man bis zum Termin.": "Quali articolazioni, per quanto tempo rigide al mattino, quanto gonfie. È proprio ciò che chiede la reumatologia, ed è proprio ciò che si dimentica prima della visita.",
  "Steif am Morgen": "Rigidità al mattino",
  "Unter 30 Minuten": "Meno di 30 minuti",
  "30 bis 60 Minuten": "Da 30 a 60 minuti",
  "Ueber eine Stunde": "Più di un'ora",
  "geschwollene Gelenke": "articolazioni gonfie",
  "Rheumafaktor": "Fattore reumatoide",
  "Hilft bei der Diagnose. Fuer den Verlauf sagen CRP, BSG und die Gelenke mehr.": "Aiuta nella diagnosi. Per il decorso dicono di più PCR, VES e le articolazioni.",
  "Anti-CCP": "Anti-CCP",
  "Sehr spezifisch fuer rheumatoide Arthritis. Wird meist einmal bestimmt, nicht laufend.": "Molto specifici per l'artrite reumatoide. Di solito si misurano una volta, non ripetutamente.",
  "ALT (GPT)": "ALT (GPT)",
  "Leber": "Fegato",
  "Leberwert. Wird unter Methotrexat und einigen anderen Medikamenten regelmaessig kontrolliert.": "Valore epatico. Si controlla regolarmente con il metotrexato e alcuni altri farmaci.",
  "Mediterran, mit Fisch": "Mediterraneo, con pesce",
  "Omega-3-Fettsaeuren lindern Gelenkbeschwerden in Studien leicht. Sie ersetzen keine Basistherapie.": "Gli acidi grassi omega-3 alleviano leggermente i disturbi articolari negli studi. Non sostituiscono la terapia di fondo.",
  "Alkohol unter Methotrexat": "Alcol con il metotrexato",
  "Belastet zusammen die Leber. Wie viel vertretbar ist, in der Sprechstunde klaeren.": "Insieme affaticano il fegato. Quanto sia accettabile è una domanda per l'ambulatorio.",
  "Nicht rauchen": "Non fumare",
  "Rauchen verschlechtert den Verlauf und das Ansprechen auf Medikamente deutlich.": "Il fumo peggiora chiaramente il decorso e la risposta ai farmaci.",
  "Ist das Ziel Remission erreicht, und wenn nicht, was ist der naechste Schritt?": "L'obiettivo della remissione è raggiunto, e se no, qual è il prossimo passo?",
  "Welche Kontrollen brauche ich unter meiner Basistherapie, und wie oft?": "Quali controlli mi servono con la mia terapia di fondo, e quanto spesso?",
  "Morbus Crohn oder Colitis ulcerosa": "Morbo di Crohn o colite ulcerosa",
  "CED": "MICI",
  "Bauch, Stuhl und Blut darin. Unangenehm aufzuschreiben, und gerade deshalb wertvoll: genau diese Zahlen entscheiden ueber die Behandlung.": "Pancia, feci e sangue nelle feci. Sgradevole da annotare, e prezioso proprio per questo: questi numeri decidono la terapia.",
  "Stuhlgaenge heute": "Evacuazioni oggi",
  "0 bis 3": "Da 0 a 3",
  "4 bis 6": "Da 4 a 6",
  "7 oder mehr": "7 o più",
  "Blut im Stuhl": "sangue nelle feci",
  "naechtlicher Stuhlgang": "evacuazione notturna",
  "Calprotectin im Stuhl": "Calprotectina fecale",
  "Darm": "Intestino",
  "Zeigt Entzuendung im Darm, ohne Spiegelung. Steigt oft, bevor Beschwerden kommen.": "Mostra l'infiammazione dell'intestino senza endoscopia. Spesso sale prima dei sintomi.",
  "Persoenliche Vertraeglichkeit zaehlt": "Conta la tolleranza personale",
  "Es gibt keine Diaet fuer alle. Ein Ernaehrungstagebuch ist ehrlicher als jede Liste.": "Non esiste una dieta per tutti. Un diario alimentare è più onesto di qualsiasi lista.",
  "Im Schub: schonend und ballaststoffarm nur nach Ruecksprache": "Durante una riacutizzazione: leggera e povera di fibre solo su consiglio",
  "Bei Engstellen kann es noetig sein, sonst sind Ballaststoffe eher hilfreich. Das entscheidet die Gastroenterologie.": "Con le stenosi può essere necessario, altrimenti le fibre tendono ad aiutare. Decide la gastroenterologia.",
  "Eisen, B12, Vitamin D messen lassen": "Far misurare ferro, B12, vitamina D",
  "Blutverlust und Entzuendung zehren daran, besonders bei Befall des Duenndarms.": "Perdita di sangue e infiammazione li consumano, soprattutto se è coinvolto l'intestino tenue.",
  "Wie ist mein Calprotectin im Verlauf, und wann wird wieder gespiegelt?": "Come va la mia calprotectina nel tempo, e quando è la prossima endoscopia?",
  "Was tue ich bei Blut im Stuhl oder Fieber, und wen rufe ich an?": "Cosa faccio con sangue nelle feci o febbre, e chi chiamo?",
  "Wie geht es dir": "Come stai",
  "sehr schlecht": "molto male",
  "sehr gut": "molto bene",
  "Muedigkeit": "Stanchezza",
  "wach": "vigile",
  "erschoepft": "allo stremo",
  "Schmerz": "Dolore",
  "stark": "forte",
  "Weiche Polenta mit Ei und Spinat": "Polenta morbida con uovo e spinaci",
  "Warm, weich, in einem Topf. Gut an Tagen, an denen der Bauch empfindlich ist.": "Calda, morbida, in una sola pentola. Buona nei giorni in cui la pancia è sensibile.",
  "60 g Instant-Polenta (Maisgriess, glutenfrei gekennzeichnet)": "60 g di polenta istantanea (farina di mais, etichettata senza glutine)",
  "250 ml Wasser oder glutenfreie Bruehe": "250 ml di acqua o brodo senza glutine",
  "1 Ei": "1 uovo",
  "1 Handvoll Babyspinat": "1 manciata di spinacini",
  "1 EL Parmesan, etwas Olivenoel": "1 cucchiaio di parmigiano, un filo d'olio d'oliva",
  "Wasser aufkochen, Polenta einruehren, 5 Minuten leise ruehren.": "Porta l'acqua a bollore, versa la polenta e mescola piano per 5 minuti.",
  "Mulde druecken, Ei hineinschlagen, Deckel drauf, 4 Minuten.": "Fai una conca, rompi l'uovo dentro, coperchio, 4 minuti.",
  "Spinat und Parmesan darueber, Oel dazu.": "Sopra spinaci e parmigiano, aggiungi l'olio.",
  "Maisgriess ist von Natur aus glutenfrei, wird aber oft in Muehlen mit Weizen verarbeitet. Auf das Zeichen achten.": "La farina di mais è naturalmente senza glutine, ma spesso viene macinata insieme al frumento. Controlla il simbolo.",
  "Reis mit Sardinen, Zitrone und Petersilie": "Riso con sardine, limone e prezzemolo",
  "Aus dem Vorrat, mit Kalzium aus den Graeten und Omega-3. Fertigreis macht es zu zehn Minuten.": "Dalla dispensa, con il calcio delle lische e gli omega-3. Con il riso già cotto bastano dieci minuti.",
  "1 Beutel vorgegarter Reis (Zutaten pruefen)": "1 busta di riso precotto (controlla gli ingredienti)",
  "1 Dose Sardinen in Olivenoel": "1 scatoletta di sardine sott'olio d'oliva",
  "1/2 Zitrone": "1/2 limone",
  "Petersilie, Pfeffer": "Prezzemolo, pepe",
  "Reis erwaermen.": "Scalda il riso.",
  "Sardinen mit dem Oel darueber, grob zerdruecken.": "Sardine con il loro olio sopra, spezzale grossolanamente.",
  "Zitrone, Petersilie, Pfeffer.": "Limone, prezzemolo, pepe.",
  "Gewuerzter Fertigreis kann Gluten enthalten, natur ist sicher.": "Il riso pronto condito può contenere glutine, quello al naturale è sicuro.",
  "Linsensalat mit Paprika und Zitrone": "Insalata di lenticchie con peperone e limone",
  "Eisen aus den Linsen, Vitamin C aus Paprika und Zitrone hilft bei der Aufnahme.": "Ferro dalle lenticchie, e la vitamina C di peperone e limone ne aiuta l'assorbimento.",
  "1 Glas oder Dose gekochte Linsen": "1 vasetto o scatola di lenticchie cotte",
  "1 rote Paprika": "1 peperone rosso",
  "1/2 rote Zwiebel": "1/2 cipolla rossa",
  "Saft einer Zitrone, 2 EL Olivenoel": "Succo di un limone, 2 cucchiai di olio d'oliva",
  "Petersilie, Salz": "Prezzemolo, sale",
  "Linsen abspuelen.": "Sciacqua le lenticchie.",
  "Paprika und Zwiebel klein schneiden.": "Taglia a pezzetti peperone e cipolla.",
  "Alles mischen, haelt zwei Tage im Kuehlschrank.": "Mescola tutto, si conserva due giorni in frigo.",
  "Kaffee und schwarzer Tee zum Essen mindern die Eisenaufnahme, lieber eine Stunde Abstand.": "Caffè e tè nero durante il pasto riducono l'assorbimento del ferro, meglio a un'ora di distanza.",
  "Lachs mit Quinoa und Brokkoli": "Salmone con quinoa e broccoli",
  "Ein Topf, eine Pfanne, zwanzig Minuten. Omega-3 und Eiweiss fuer zwei Mahlzeiten.": "Una pentola, una padella, venti minuti. Omega-3 e proteine per due pasti.",
  "120 g Quinoa": "120 g di quinoa",
  "2 Lachsfilets": "2 filetti di salmone",
  "1 Brokkoli": "1 broccolo",
  "Olivenoel, Zitrone, Salz": "Olio d'oliva, limone, sale",
  "Quinoa gut spuelen, mit doppelter Menge Wasser 15 Minuten koecheln.": "Sciacqua bene la quinoa e falla sobbollire per 15 minuti nel doppio di acqua.",
  "Brokkoli die letzten 5 Minuten oben drauf daempfen.": "Cuoci i broccoli al vapore sopra negli ultimi 5 minuti.",
  "Lachs in der Pfanne je Seite 3 bis 4 Minuten, Zitrone darueber.": "Salmone in padella 3-4 minuti per lato, limone sopra.",
  "Quinoa ist glutenfrei, Spuelen nimmt die bitteren Saponine.": "La quinoa è senza glutine, sciacquarla elimina le saponine amare.",
  "Joghurtschale mit Nuessen und Beeren": "Ciotola di yogurt con frutta secca e frutti di bosco",
  "Kalzium und Eiweiss ohne Herd. Fuer den Morgen nach einer schlechten Nacht.": "Calcio e proteine senza fornelli. Per la mattina dopo una brutta notte.",
  "200 g Naturjoghurt oder Skyr": "200 g di yogurt bianco o skyr",
  "1 Handvoll Beeren, auch tiefgekuehlt": "1 manciata di frutti di bosco, anche surgelati",
  "1 EL Walnuesse oder Mandeln": "1 cucchiaio di noci o mandorle",
  "1 TL Leinsamen geschrotet": "1 cucchiaino di semi di lino macinati",
  "Alles in eine Schale, fertig.": "Tutto in una ciotola, fatto.",
  "Fruchtjoghurt und Muesli-Mischungen koennen Gluten enthalten, natur ist sicher.": "Gli yogurt alla frutta e i mix di muesli possono contenere glutine, quelli al naturale sono sicuri.",
  "Kartoffeln mit Ei und Kraeuterjoghurt": "Patate con uovo e yogurt alle erbe",
  "Mild und satt. Schale weglassen macht es noch schonender fuer den Bauch.": "Delicato e saziante. Sbucciare le patate lo rende ancora più leggero per la pancia.",
  "500 g Kartoffeln": "500 g di patate",
  "2 Eier": "2 uova",
  "150 g Joghurt": "150 g di yogurt",
  "Schnittlauch oder Dill, Salz": "Erba cipollina o aneto, sale",
  "Kartoffeln 20 Minuten kochen, Eier die letzten 9 Minuten mitkochen.": "Fai bollire le patate 20 minuti, aggiungi le uova negli ultimi 9.",
  "Joghurt mit Kraeutern und Salz verruehren.": "Mescola lo yogurt con erbe e sale.",
  "Alles zusammen auf den Teller.": "Tutto insieme nel piatto.",
  "Kocht man die doppelte Menge Kartoffeln, ist morgen schon etwas da.": "Se cuoci il doppio delle patate, domani c'è già qualcosa di pronto.",
  "Huehnersuppe mit Reis und Karotte": "Zuppa di pollo con riso e carota",
  "Die Suppe fuer Infekte und schlechte Bauchtage. Friert gut ein.": "La zuppa per le infezioni e i giorni no della pancia. Si congela bene.",
  "2 Huehnerbrustfilets oder -keulen": "2 petti o cosce di pollo",
  "2 Karotten, 1 Stueck Sellerie": "2 carote, 1 pezzo di sedano rapa",
  "80 g Reis": "80 g di riso",
  "1,2 l Wasser, Salz, Lorbeer": "1,2 l di acqua, sale, alloro",
  "Huhn mit Gemuese und Lorbeer im Wasser 20 Minuten leise koecheln.": "Fai sobbollire il pollo con le verdure e l'alloro nell'acqua per 20 minuti.",
  "Huhn herausnehmen, zerzupfen, Reis in die Bruehe, 12 Minuten.": "Togli il pollo, sfilaccialo, metti il riso nel brodo, 12 minuti.",
  "Huhn zurueck, salzen.": "Rimetti il pollo, regola di sale.",
  "Selbst gekocht ist die Bruehe sicher glutenfrei, Wuerfel und Pulver oft nicht.": "Il brodo fatto in casa è sicuramente senza glutine, dadi e granulati spesso no.",
  "Kichererbsen und Suesskartoffel vom Blech": "Ceci e patate dolci al forno",
  "Fuenf Minuten Arbeit, der Ofen macht den Rest. Reicht fuer drei Tage.": "Cinque minuti di lavoro, il forno fa il resto. Basta per tre giorni.",
  "1 Dose Kichererbsen": "1 scatola di ceci",
  "2 Suesskartoffeln": "2 patate dolci",
  "1 rote Zwiebel": "1 cipolla rossa",
  "Olivenoel, Paprikapulver, Kreuzkuemmel, Salz": "Olio d'oliva, paprika, cumino, sale",
  "Tahin oder Joghurt zum Darueber": "Tahina o yogurt da versare sopra",
  "Ofen auf 210 Grad.": "Forno a 210 °C.",
  "Alles grob schneiden, mit Oel und Gewuerzen aufs Blech.": "Taglia tutto a pezzi grossi, sulla teglia con olio e spezie.",
  "25 Minuten, einmal wenden.": "25 minuti, gira una volta.",
  "Gewuerzmischungen koennen Weizenmehl als Rieselhilfe enthalten, Einzelgewuerze sind sicherer.": "I mix di spezie possono contenere farina di frumento come antiagglomerante, le spezie singole sono più sicure.",
  "Raeucherforelle mit Kartoffeln und Gurke": "Trota affumicata con patate e cetriolo",
  "Regional, fertig geraeuchert, mild. Omega-3 ohne Pfanne.": "Locale, già affumicata, delicata. Omega-3 senza padella.",
  "1 Raeucherforellenfilet": "1 filetto di trota affumicata",
  "400 g Kartoffeln": "400 g di patate",
  "1/2 Gurke": "1/2 cetriolo",
  "Zitrone, Dill, Olivenoel": "Limone, aneto, olio d'oliva",
  "Kartoffeln kochen.": "Fai bollire le patate.",
  "Gurke in Scheiben, mit Zitrone und Dill.": "Cetriolo a fette, con limone e aneto.",
  "Forelle zerpfluecken und dazu.": "Sfalda la trota accanto.",
  "Kren aus dem Glas kann Weizen enthalten, frisch gerieben ist sicher.": "Il rafano in vasetto può contenere frumento, quello grattugiato fresco è sicuro.",
  "Buchweizenbrei mit Apfel und Zimt": "Crema di grano saraceno con mela e cannella",
  "Buchweizen ist trotz des Namens kein Weizen. Warm, nussig, mit Eisen und Ballaststoffen.": "Nonostante il nome, il grano saraceno non è frumento. Caldo, dal gusto di nocciola, con ferro e fibre.",
  "50 g Buchweizenflocken (glutenfrei gekennzeichnet)": "50 g di fiocchi di grano saraceno (etichettati senza glutine)",
  "200 ml Milch oder Pflanzendrink": "200 ml di latte o bevanda vegetale",
  "1 Apfel gerieben": "1 mela grattugiata",
  "Zimt, 1 TL Nussmus": "Cannella, 1 cucchiaino di crema di frutta secca",
  "Flocken mit Milch 5 Minuten koecheln.": "Fai sobbollire i fiocchi nel latte per 5 minuti.",
  "Apfel und Zimt einruehren.": "Incorpora mela e cannella.",
  "Nussmus darauf.": "Crema di frutta secca sopra.",
  "Auch bei Buchweizen auf das Glutenfrei-Zeichen achten, wegen Verunreinigung in der Muehle.": "Anche per il grano saraceno controlla il simbolo senza glutine, per la contaminazione al mulino.",
  "Omelett mit Zucchini und Feta": "Frittata con zucchine e feta",
  "Zehn Minuten, eine Pfanne, viel Eiweiss. Geht auch zum Abendessen.": "Dieci minuti, una padella, tante proteine. Va bene anche per cena.",
  "3 Eier": "3 uova",
  "1/2 Zucchini, fein gerieben": "1/2 zucchina, grattugiata fine",
  "30 g Feta": "30 g di feta",
  "Olivenoel, Pfeffer": "Olio d'oliva, pepe",
  "Zucchini in Oel 2 Minuten anbraten.": "Rosola la zucchina nell'olio per 2 minuti.",
  "Verquirlte Eier darueber, bei kleiner Hitze stocken lassen.": "Versa sopra le uova sbattute, lascia rapprendere a fuoco basso.",
  "Feta darueber, zuklappen.": "Feta sopra, chiudi a metà.",
  "Mit Reiswaffeln oder Kartoffeln vom Vortag ist es eine ganze Mahlzeit.": "Con gallette di riso o patate del giorno prima è un pasto completo.",
  "Weisse Bohnen in Tomate mit Rosmarin": "Fagioli bianchi al pomodoro con rosmarino",
  "Zwei Dosen und ein Zweig Rosmarin. Mediterran, eisenreich und billig.": "Due scatole e un rametto di rosmarino. Mediterraneo, ricco di ferro ed economico.",
  "1 Dose weisse Bohnen": "1 scatola di fagioli bianchi",
  "1 Dose gehackte Tomaten": "1 scatola di pomodori a pezzi",
  "1 Knoblauchzehe, 1 Zweig Rosmarin": "1 spicchio d'aglio, 1 rametto di rosmarino",
  "Olivenoel, Salz, Pfeffer": "Olio d'oliva, sale, pepe",
  "Knoblauch und Rosmarin in Oel kurz anschwitzen.": "Fai appassire brevemente aglio e rosmarino nell'olio.",
  "Tomaten und abgespuelte Bohnen dazu, 10 Minuten koecheln.": "Aggiungi pomodori e fagioli sciacquati, fai sobbollire 10 minuti.",
  "Mit Oel und Pfeffer fertig.": "Completa con olio e pepe.",
  "Dazu glutenfreies Brot oder Polenta. Bei empfindlichem Bauch die Menge klein halten.": "Accompagna con pane senza glutine o polenta. Con la pancia sensibile tieni piccola la porzione.",
  "Mehrmals Gluten in zwei Wochen. Versteckte Quellen suchen: Sojasauce, Bruehen, Hafer, gemeinsamer Toaster. Halten Beschwerden trotz Diaet an, gehoert das zum Termin.": "Glutine più volte in due settimane. Cerca le fonti nascoste: salsa di soia, brodi, avena, tostapane in comune. Se i disturbi continuano nonostante la dieta, va detto alla visita.",
  "Kann eine Entzuendung von Rippenfell oder Herzbeutel sein. Zeitnah aerztlich abklaeren lassen, bei Atemnot sofort.": "Può essere un'infiammazione della pleura o del pericardio. Fallo valutare presto da un medico, subito se manca il respiro.",
  "Kann Eiweiss im Urin bedeuten, ein fruehes Zeichen einer Nierenbeteiligung. Urin untersuchen lassen.": "Può indicare proteine nelle urine, un segno precoce di coinvolgimento renale. Fai analizzare le urine.",
  "Wassereinlagerungen koennen mit der Niere zusammenhaengen. Ansprechen und den Urin pruefen lassen.": "La ritenzione di liquidi può dipendere dai reni. Parlane e fai controllare le urine.",
  "Lunge, Herz oder Blutarmut koennen dahinterstecken. Zeitnah abklaeren, bei Atemnot in Ruhe sofort.": "Possono esserci dietro polmoni, cuore o anemia. Fallo valutare presto, subito se manca il respiro a riposo.",
  "Kann ein Schub oder ein Infekt sein, unter Immunsuppression zaehlt beides. Mit der Praxis klaeren.": "Può essere una riacutizzazione o un'infezione, e con l'immunosoppressione contano entrambe. Chiarisci con l'ambulatorio.",
  "Oft viel Sonne abbekommen. UV-Licht kann Haut- und Allgemeinschuebe ausloesen, Schutz lohnt sich jeden Tag.": "Spesso molto sole. La luce UV può scatenare riacutizzazioni cutanee e generali, proteggersi conviene ogni giorno.",
  "Alfalfa-Sprossen: bei Lupus besser weglassen.": "Germogli di erba medica: con il lupus meglio evitarli.",
  "Ein ganz geschwollener Finger oder Zeh ist typisch fuer eine Psoriasis-Arthritis. Frueh in der Dermatologie oder Rheumatologie ansprechen.": "Un dito della mano o del piede tutto gonfio è tipico dell'artrite psoriasica. Parlane presto in dermatologia o reumatologia.",
  "Halsentzuendungen durch Streptokokken koennen einen Psoriasis-Schub ausloesen, unter systemischer Behandlung zaehlt jeder Infekt. Der Praxis sagen.": "Le faringiti da streptococco possono scatenare una riacutizzazione della psoriasi, e con una terapia sistemica conta ogni infezione. Dillo all'ambulatorio.",
  "Enthaelt Alkohol. Bei Psoriasis und unter Methotrexat zurueckhaltend, beim Kochen verfliegt nicht alles.": "Contiene alcol. Con la psoriasi e con il metotrexato meglio limitarlo, la cottura non lo elimina del tutto.",
  "Kann bedeuten, dass die Dosis zu hoch ist. TSH kontrollieren lassen.": "Può significare che la dose è troppo alta. Fai controllare il TSH.",
  "Die Tablette oefter vergessen oder mit Essen genommen. Das verschiebt den TSH-Wert; vor der naechsten Kontrolle ansprechen.": "La compressa è stata spesso dimenticata o presa col cibo. Questo sposta il TSH; parlane prima del prossimo controllo.",
  "Soja: nicht kurz nach der Schilddruesentablette essen, sonst wird weniger Hormon aufgenommen.": "Soia: non mangiarla subito dopo la compressa per la tiroide, altrimenti si assorbe meno ormone.",
  "Unter Basistherapie und Biologika koennen Infekte schwerer verlaufen. Die Praxis fragen, ob an den Medikamenten etwas zu aendern ist.": "Con la terapia di fondo e i farmaci biologici le infezioni possono essere più gravi. Chiedi all'ambulatorio se va cambiato qualcosa nei farmaci.",
  "An mehreren Tagen ueber eine Stunde steif am Morgen. Das spricht fuer aktive Entzuendung und gehoert vor den naechsten Routinetermin.": "Rigidità mattutina oltre un'ora in diversi giorni. Indica un'infiammazione attiva e va segnalata prima della prossima visita di routine.",
  "Enthaelt Alkohol. Unter Methotrexat zurueckhaltend, beim Kochen verfliegt nicht alles.": "Contiene alcol. Con il metotrexato meglio limitarlo, la cottura non lo elimina del tutto.",
  "Kann einen Schub anzeigen. Der Praxis melden, mit Fieber oder vielen Stuhlgaengen noch am selben Tag.": "Può indicare una riacutizzazione. Segnalalo all'ambulatorio, in giornata se c'è febbre o se le evacuazioni sono molte.",
  "Bei CED kann Fieber Schub, Abszess oder Infekt bedeuten, unter Immunsuppression zaehlt alles davon. Mit der Praxis klaeren.": "Nelle MICI la febbre può significare riacutizzazione, ascesso o infezione, e con l'immunosoppressione conta tutto. Chiarisci con l'ambulatorio.",
  "Stuhlgang in der Nacht spricht eher fuer Entzuendung als fuer einen gereizten Darm. Beim Termin ansprechen.": "Evacuare di notte fa pensare più a un'infiammazione che a un intestino irritabile. Parlane alla visita.",
  "An mehreren Tagen sieben oder mehr Stuhlgaenge. Das kann ein Schub sein; der Praxis melden.": "Sette o più evacuazioni in diversi giorni. Può essere una riacutizzazione; segnalalo all'ambulatorio."
 },
 "fr": {
  "Zoeliakie": "Maladie cœliaque",
  "Glutenfreie Ernaehrung ist die Behandlung. Die App fragt jeden Tag nach dem Essen und behaelt die Werte im Blick, die bei Zoeliakie kippen.": "Le régime sans gluten est le traitement. L'app pose chaque jour une question sur les repas et garde un œil sur les valeurs qui baissent souvent dans la maladie cœliaque.",
  "Bauch": "Ventre",
  "ruhig": "calme",
  "starke Beschwerden": "troubles importants",
  "Der Tag beim Essen": "La journée à table",
  "Alles sicher": "Tout était sûr",
  "Etwas war unsicher": "Quelque chose était incertain",
  "Gluten bekommen": "Gluten ingéré",
  "Weizen, Roggen, Gerste, Dinkel und alles daraus": "Blé, seigle, orge, épeautre et tout ce qui en est fait",
  "Schon kleine Mengen schaedigen die Duenndarmschleimhaut, auch ohne spuerbare Beschwerden.": "Même de petites quantités abîment la muqueuse de l'intestin grêle, avec ou sans symptômes.",
  "Hafer nur als glutenfrei gekennzeichnet": "Avoine seulement si étiquetée sans gluten",
  "Normaler Hafer ist fast immer verunreinigt. Ein kleiner Teil der Betroffenen vertraegt auch reinen Hafer nicht; das zeigt der Verlauf, nicht ein Gefuehl.": "L'avoine ordinaire est presque toujours contaminée. Une petite partie des personnes réagit aussi à l'avoine pure ; c'est l'évolution qui le montre, pas une impression.",
  "Sojasauce, Malz, Bruehen, Fertigsaucen": "Sauce soja, malt, bouillons, sauces toutes prêtes",
  "Die haeufigsten versteckten Quellen. Das Zutatenverzeichnis jedes Mal lesen, Rezepturen aendern sich.": "Les sources cachées les plus fréquentes. Lis la liste d'ingrédients à chaque fois, les recettes changent.",
  "Eisen, Kalzium, Vitamin D, Folsaeure, B12 im Blick": "Fer, calcium, vitamine D, folates, B12 à surveiller",
  "Bei Zoeliakie oft niedrig, besonders am Anfang. Messen lassen statt auf Verdacht ergaenzen.": "Souvent bas dans la maladie cœliaque, surtout au début. Mieux vaut les faire doser que se supplémenter au hasard.",
  "Brauche ich eine Ueberweisung zur Diaetologie?": "Ai-je besoin d'une orientation vers un diététicien ?",
  "Systemischer Lupus (SLE)": "Lupus systémique (LES)",
  "Lupus": "Lupus",
  "Lupus zeigt sich ueberall ein wenig. Die App sammelt Gelenke, Haut, Kopf und Muedigkeit an einer Stelle, damit beim Termin das Muster sichtbar wird.": "Le lupus se manifeste un peu partout. L'app rassemble articulations, peau, tête et fatigue au même endroit, pour que le schéma soit visible en consultation.",
  "Gelenke": "Articulations",
  "frei": "libres",
  "steif, geschwollen": "raides, gonflées",
  "Kopf klar": "Tête claire",
  "klar": "claire",
  "im Nebel": "dans le brouillard",
  "Sonne und Licht": "Soleil et lumière",
  "Geschuetzt": "À l'abri du soleil",
  "Etwas abbekommen": "Un peu de soleil",
  "Viel abbekommen": "Beaucoup de soleil",
  "Mediterranes Muster": "Un modèle méditerranéen",
  "Gemuese, Huelsenfruechte, Olivenoel, Fisch. Es gibt Hinweise auf weniger Krankheitsaktivitaet und ein besseres Herzrisiko, aber keine Diaet, die Lupus heilt.": "Légumes, légumineuses, huile d'olive, poisson. Certains signes indiquent une activité de la maladie plus faible et un meilleur risque cardiaque, mais aucun régime ne guérit le lupus.",
  "Alfalfa-Sprossen": "Germes de luzerne",
  "Enthalten L-Canavanin, das in Berichten Lupus-aehnliche Schuebe ausgeloest hat. Die Belege sind alt und duenn, der Verzicht kostet nichts.": "Contiennent de la L-canavanine, qui a déclenché dans des cas rapportés des poussées ressemblant au lupus. Les données sont anciennes et minces, y renoncer ne coûte rien.",
  "Echinacea und andere Immun-Booster": "Échinacée et autres stimulants immunitaires",
  "Sollen das Immunsystem anregen, genau das ist bei Lupus nicht das Ziel. Vorher in der Sprechstunde fragen.": "Destinés à stimuler le système immunitaire, ce qui n'est pas le but dans le lupus. Demande d'abord en consultation.",
  "Kalzium und Vitamin D bei Kortison": "Calcium et vitamine D sous cortisone",
  "Kortison kostet Knochen. Ob und wie viel ergaenzt wird, entscheidet die Aerztin nach Messung.": "La cortisone fragilise les os. Le médecin décide après un dosage s'il faut une supplémentation et à quelle dose.",
  "Wie aktiv ist mein Lupus gerade, in Zahlen?": "Quelle est l'activité de mon lupus en ce moment, en chiffres ?",
  "Wann wurde zuletzt der Urin auf Eiweiss geprueft?": "Quand mes urines ont-elles été contrôlées pour la dernière fois pour les protéines ?",
  "Wann ist die naechste Netzhautkontrolle faellig?": "À quand le prochain contrôle de la rétine ?",
  "Psoriasis": "Psoriasis",
  "Haut, Juckreiz und Gelenke. Gelenkbeschwerden bei Psoriasis gehoeren frueh angesprochen, weil eine Psoriasis-Arthritis behandelbar ist, bevor sie Schaden macht.": "Peau, démangeaisons et articulations. Les douleurs articulaires avec un psoriasis doivent être signalées tôt, car un rhumatisme psoriasique se traite avant de causer des dégâts.",
  "Haut": "Peau",
  "stark befallen": "très étendu",
  "Juckreiz": "Démangeaisons",
  "keiner": "aucune",
  "quaelend": "insupportables",
  "Haut gepflegt und behandelt": "Peau soignée et traitée",
  "Wie geplant": "Comme prévu",
  "Teilweise": "En partie",
  "Heute nicht": "Pas aujourd'hui",
  "neue Plaques": "nouvelles plaques",
  "Kopfhaut": "cuir chevelu",
  "Naegel": "ongles",
  "Hautrisse": "peau crevassée",
  "geschwollener Finger oder Zeh": "doigt ou orteil gonflé",
  "Infekt, Halsweh": "infection, mal de gorge",
  "Gewicht und mediterranes Muster": "Poids et modèle méditerranéen",
  "Bei Uebergewicht bessert Abnehmen die Haut in Studien messbar und laesst Medikamente besser wirken.": "En cas de surpoids, perdre quelques kilos améliore la peau de façon mesurable dans les études et aide le traitement à mieux agir.",
  "Alkohol": "Alcool",
  "Haengt mit schwereren Verlaeufen zusammen und vertraegt sich mit einigen Medikamenten schlecht, etwa Methotrexat.": "Associé à des formes plus sévères et peu compatible avec certains médicaments, comme le méthotrexate.",
  "Glutenfrei nur mit Grund": "Sans gluten seulement avec une raison",
  "Hilft in Studien nur, wenn Zoeliakie-Antikoerper nachweisbar sind. Dann aber deutlich. Testen lassen statt raten.": "Dans les études, cela n'aide que si des anticorps de la maladie cœliaque sont présents. Alors cela aide nettement. Fais le test, ne devine pas.",
  "Koennten meine Gelenkbeschwerden eine Psoriasis-Arthritis sein?": "Mes douleurs articulaires pourraient-elles être un rhumatisme psoriasique ?",
  "Wie gross ist der befallene Hautanteil, und ist eine systemische Behandlung sinnvoll?": "Quelle surface de peau est touchée, et un traitement systémique serait-il pertinent ?",
  "Sollen Blutdruck, Blutfette und Blutzucker kontrolliert werden?": "Faut-il contrôler la tension, les lipides et la glycémie ?",
  "Hashimoto-Thyreoiditis": "Thyroïdite de Hashimoto",
  "Hashimoto": "Hashimoto",
  "Viel haengt an einer Tablette zur richtigen Zeit und an einem Wert. Die App fragt nach dem einen und behaelt den anderen im Verlauf.": "Beaucoup dépend d'un comprimé pris au bon moment et d'une valeur. L'app pose la question du premier et suit la seconde dans le temps.",
  "Kaelteempfinden": "Sensation de froid",
  "normal": "normale",
  "staendig kalt": "toujours froid",
  "Schilddruesentablette": "Comprimé pour la thyroïde",
  "Nuechtern genommen": "Pris à jeun",
  "Mit Essen oder Kaffee": "Avec repas ou café",
  "Vergessen": "Oublié",
  "kaelteempfindlich": "sensible au froid",
  "Gewicht steigt": "poids en hausse",
  "trockene Haut": "peau sèche",
  "Stimmung gedrueckt": "moral en baisse",
  "fT4": "T4 libre",
  "Schilddruese": "Thyroïde",
  "Das freie Schilddruesenhormon. Zusammen mit dem TSH sagt es, ob die Dosis passt. Blut am besten vor der Tabletteneinnahme abnehmen lassen.": "L'hormone thyroïdienne libre. Avec la TSH, elle montre si la dose convient. Faire la prise de sang de préférence avant le comprimé.",
  "TPO-Antikoerper": "Anticorps anti-TPO",
  "Bestaetigen die Autoimmunerkrankung. Ihre Hoehe steuert nicht die Behandlung und muss nicht laufend gemessen werden.": "Confirment la maladie auto-immune. Leur taux ne guide pas le traitement et n'a pas besoin d'être mesuré régulièrement.",
  "Tablette nuechtern, mit Wasser": "Comprimé à jeun, avec de l'eau",
  "30 bis 60 Minuten vor dem Fruehstueck, immer gleich. Kaffee, Soja und Ballaststoffe dazwischen verringern die Aufnahme.": "30 à 60 minutes avant le petit-déjeuner, toujours de la même façon. Café, soja et fibres entre-temps réduisent l'absorption.",
  "Kalzium, Eisen und Magnesium mit Abstand": "Calcium, fer et magnésium à distance",
  "Mindestens vier Stunden Abstand zur Tablette, sonst wird weniger Hormon aufgenommen.": "Au moins quatre heures d'écart avec le comprimé, sinon moins d'hormone est absorbée.",
  "Jod und Selen nicht auf eigene Faust": "Iode et sélénium pas de ta propre initiative",
  "Normale Ernaehrung mit Jodsalz reicht. Hoch dosierte Praeparate koennen schaden, der Nutzen von Selen ist nicht gesichert.": "Une alimentation normale avec du sel iodé suffit. Les produits très dosés peuvent nuire, le bénéfice du sélénium n'est pas établi.",
  "Passt meine Dosis zum letzten TSH-Wert, und wann wird wieder kontrolliert?": "Ma dose convient-elle à la dernière TSH, et quand a lieu le prochain contrôle ?",
  "Muss ich den Abstand zu anderen Medikamenten oder Ergaenzungen aendern?": "Dois-je modifier l'écart avec d'autres médicaments ou compléments ?",
  "Rheumatoide Arthritis": "Polyarthrite rhumatoïde",
  "Arthritis": "Polyarthrite",
  "Welche Gelenke, wie lange steif am Morgen, wie geschwollen. Genau das fragt die Rheumatologie, und genau das vergisst man bis zum Termin.": "Quelles articulations, combien de temps raides le matin, à quel point gonflées. C'est exactement ce que demande la rhumatologie, et exactement ce qu'on oublie avant le rendez-vous.",
  "Steif am Morgen": "Raideur matinale",
  "Unter 30 Minuten": "Moins de 30 minutes",
  "30 bis 60 Minuten": "30 à 60 minutes",
  "Ueber eine Stunde": "Plus d'une heure",
  "geschwollene Gelenke": "articulations gonflées",
  "Rheumafaktor": "Facteur rhumatoïde",
  "Hilft bei der Diagnose. Fuer den Verlauf sagen CRP, BSG und die Gelenke mehr.": "Aide au diagnostic. Pour le suivi, la CRP, la VS et les articulations en disent plus.",
  "Anti-CCP": "Anti-CCP",
  "Sehr spezifisch fuer rheumatoide Arthritis. Wird meist einmal bestimmt, nicht laufend.": "Très spécifiques de la polyarthrite rhumatoïde. En général dosés une fois, pas à répétition.",
  "ALT (GPT)": "ALAT (GPT)",
  "Leber": "Foie",
  "Leberwert. Wird unter Methotrexat und einigen anderen Medikamenten regelmaessig kontrolliert.": "Valeur hépatique. Contrôlée régulièrement sous méthotrexate et quelques autres médicaments.",
  "Mediterran, mit Fisch": "Méditerranéen, avec du poisson",
  "Omega-3-Fettsaeuren lindern Gelenkbeschwerden in Studien leicht. Sie ersetzen keine Basistherapie.": "Les acides gras oméga-3 soulagent légèrement les douleurs articulaires dans les études. Ils ne remplacent pas le traitement de fond.",
  "Alkohol unter Methotrexat": "Alcool sous méthotrexate",
  "Belastet zusammen die Leber. Wie viel vertretbar ist, in der Sprechstunde klaeren.": "Ensemble, ils sollicitent le foie. La quantité acceptable est une question pour la consultation.",
  "Nicht rauchen": "Ne pas fumer",
  "Rauchen verschlechtert den Verlauf und das Ansprechen auf Medikamente deutlich.": "Le tabac aggrave nettement l'évolution et la réponse aux médicaments.",
  "Ist das Ziel Remission erreicht, und wenn nicht, was ist der naechste Schritt?": "L'objectif de rémission est-il atteint, et sinon, quelle est la prochaine étape ?",
  "Welche Kontrollen brauche ich unter meiner Basistherapie, und wie oft?": "Quels contrôles me faut-il sous mon traitement de fond, et à quelle fréquence ?",
  "Morbus Crohn oder Colitis ulcerosa": "Maladie de Crohn ou rectocolite hémorragique",
  "CED": "MICI",
  "Bauch, Stuhl und Blut darin. Unangenehm aufzuschreiben, und gerade deshalb wertvoll: genau diese Zahlen entscheiden ueber die Behandlung.": "Ventre, selles et sang dans les selles. Désagréable à noter, et précieux justement pour cela : ces chiffres décident du traitement.",
  "Stuhlgaenge heute": "Selles aujourd'hui",
  "0 bis 3": "0 à 3",
  "4 bis 6": "4 à 6",
  "7 oder mehr": "7 ou plus",
  "Blut im Stuhl": "sang dans les selles",
  "naechtlicher Stuhlgang": "selles la nuit",
  "Calprotectin im Stuhl": "Calprotectine fécale",
  "Darm": "Intestin",
  "Zeigt Entzuendung im Darm, ohne Spiegelung. Steigt oft, bevor Beschwerden kommen.": "Montre l'inflammation de l'intestin sans endoscopie. Monte souvent avant les symptômes.",
  "Persoenliche Vertraeglichkeit zaehlt": "La tolérance personnelle compte",
  "Es gibt keine Diaet fuer alle. Ein Ernaehrungstagebuch ist ehrlicher als jede Liste.": "Il n'existe pas de régime pour tout le monde. Un journal alimentaire est plus honnête que n'importe quelle liste.",
  "Im Schub: schonend und ballaststoffarm nur nach Ruecksprache": "En poussée : doux et pauvre en fibres seulement sur avis",
  "Bei Engstellen kann es noetig sein, sonst sind Ballaststoffe eher hilfreich. Das entscheidet die Gastroenterologie.": "En cas de sténose, cela peut être nécessaire ; sinon, les fibres aident plutôt. C'est la gastro-entérologie qui décide.",
  "Eisen, B12, Vitamin D messen lassen": "Faire doser fer, B12, vitamine D",
  "Blutverlust und Entzuendung zehren daran, besonders bei Befall des Duenndarms.": "Les pertes de sang et l'inflammation les épuisent, surtout quand l'intestin grêle est touché.",
  "Wie ist mein Calprotectin im Verlauf, und wann wird wieder gespiegelt?": "Comment évolue ma calprotectine, et à quand la prochaine endoscopie ?",
  "Was tue ich bei Blut im Stuhl oder Fieber, und wen rufe ich an?": "Que faire en cas de sang dans les selles ou de fièvre, et qui appeler ?",
  "Wie geht es dir": "Comment vas-tu",
  "sehr schlecht": "très mal",
  "sehr gut": "très bien",
  "Muedigkeit": "Fatigue",
  "wach": "en forme",
  "erschoepft": "à bout",
  "Schmerz": "Douleur",
  "stark": "forte",
  "Weiche Polenta mit Ei und Spinat": "Polenta crémeuse à l'œuf et aux épinards",
  "Warm, weich, in einem Topf. Gut an Tagen, an denen der Bauch empfindlich ist.": "Chaude, douce, en une seule casserole. Bonne les jours où le ventre est sensible.",
  "60 g Instant-Polenta (Maisgriess, glutenfrei gekennzeichnet)": "60 g de polenta instantanée (semoule de maïs étiquetée sans gluten)",
  "250 ml Wasser oder glutenfreie Bruehe": "250 ml d'eau ou de bouillon sans gluten",
  "1 Ei": "1 œuf",
  "1 Handvoll Babyspinat": "1 poignée de pousses d'épinards",
  "1 EL Parmesan, etwas Olivenoel": "1 c. à soupe de parmesan, un filet d'huile d'olive",
  "Wasser aufkochen, Polenta einruehren, 5 Minuten leise ruehren.": "Porter l'eau à ébullition, verser la polenta, remuer doucement 5 minutes.",
  "Mulde druecken, Ei hineinschlagen, Deckel drauf, 4 Minuten.": "Creuser un puits, casser l'œuf dedans, couvrir, 4 minutes.",
  "Spinat und Parmesan darueber, Oel dazu.": "Épinards et parmesan par-dessus, ajouter l'huile.",
  "Maisgriess ist von Natur aus glutenfrei, wird aber oft in Muehlen mit Weizen verarbeitet. Auf das Zeichen achten.": "La semoule de maïs est naturellement sans gluten, mais elle est souvent moulue avec du blé. Vérifie le logo.",
  "Reis mit Sardinen, Zitrone und Petersilie": "Riz aux sardines, citron et persil",
  "Aus dem Vorrat, mit Kalzium aus den Graeten und Omega-3. Fertigreis macht es zu zehn Minuten.": "Avec les placards, le calcium des arêtes et des oméga-3. Avec du riz précuit, dix minutes suffisent.",
  "1 Beutel vorgegarter Reis (Zutaten pruefen)": "1 sachet de riz précuit (vérifier les ingrédients)",
  "1 Dose Sardinen in Olivenoel": "1 boîte de sardines à l'huile d'olive",
  "1/2 Zitrone": "1/2 citron",
  "Petersilie, Pfeffer": "Persil, poivre",
  "Reis erwaermen.": "Réchauffer le riz.",
  "Sardinen mit dem Oel darueber, grob zerdruecken.": "Les sardines avec leur huile par-dessus, émietter grossièrement.",
  "Zitrone, Petersilie, Pfeffer.": "Citron, persil, poivre.",
  "Gewuerzter Fertigreis kann Gluten enthalten, natur ist sicher.": "Le riz cuisiné tout prêt peut contenir du gluten, le riz nature est sûr.",
  "Linsensalat mit Paprika und Zitrone": "Salade de lentilles au poivron et au citron",
  "Eisen aus den Linsen, Vitamin C aus Paprika und Zitrone hilft bei der Aufnahme.": "Du fer grâce aux lentilles, et la vitamine C du poivron et du citron aide à l'absorber.",
  "1 Glas oder Dose gekochte Linsen": "1 bocal ou une boîte de lentilles cuites",
  "1 rote Paprika": "1 poivron rouge",
  "1/2 rote Zwiebel": "1/2 oignon rouge",
  "Saft einer Zitrone, 2 EL Olivenoel": "Le jus d'un citron, 2 c. à soupe d'huile d'olive",
  "Petersilie, Salz": "Persil, sel",
  "Linsen abspuelen.": "Rincer les lentilles.",
  "Paprika und Zwiebel klein schneiden.": "Couper finement le poivron et l'oignon.",
  "Alles mischen, haelt zwei Tage im Kuehlschrank.": "Tout mélanger, se garde deux jours au réfrigérateur.",
  "Kaffee und schwarzer Tee zum Essen mindern die Eisenaufnahme, lieber eine Stunde Abstand.": "Café et thé noir pendant le repas réduisent l'absorption du fer, mieux vaut une heure d'écart.",
  "Lachs mit Quinoa und Brokkoli": "Saumon, quinoa et brocoli",
  "Ein Topf, eine Pfanne, zwanzig Minuten. Omega-3 und Eiweiss fuer zwei Mahlzeiten.": "Une casserole, une poêle, vingt minutes. Des oméga-3 et des protéines pour deux repas.",
  "120 g Quinoa": "120 g de quinoa",
  "2 Lachsfilets": "2 pavés de saumon",
  "1 Brokkoli": "1 brocoli",
  "Olivenoel, Zitrone, Salz": "Huile d'olive, citron, sel",
  "Quinoa gut spuelen, mit doppelter Menge Wasser 15 Minuten koecheln.": "Bien rincer le quinoa, le faire mijoter 15 minutes dans deux fois son volume d'eau.",
  "Brokkoli die letzten 5 Minuten oben drauf daempfen.": "Cuire le brocoli à la vapeur par-dessus les 5 dernières minutes.",
  "Lachs in der Pfanne je Seite 3 bis 4 Minuten, Zitrone darueber.": "Saumon à la poêle 3 à 4 minutes par face, citron par-dessus.",
  "Quinoa ist glutenfrei, Spuelen nimmt die bitteren Saponine.": "Le quinoa est sans gluten, le rincer élimine les saponines amères.",
  "Joghurtschale mit Nuessen und Beeren": "Bol de yaourt aux noix et aux fruits rouges",
  "Kalzium und Eiweiss ohne Herd. Fuer den Morgen nach einer schlechten Nacht.": "Du calcium et des protéines sans cuisson. Pour le matin après une mauvaise nuit.",
  "200 g Naturjoghurt oder Skyr": "200 g de yaourt nature ou de skyr",
  "1 Handvoll Beeren, auch tiefgekuehlt": "1 poignée de fruits rouges, surgelés aussi",
  "1 EL Walnuesse oder Mandeln": "1 c. à soupe de noix ou d'amandes",
  "1 TL Leinsamen geschrotet": "1 c. à café de graines de lin moulues",
  "Alles in eine Schale, fertig.": "Tout dans un bol, c'est prêt.",
  "Fruchtjoghurt und Muesli-Mischungen koennen Gluten enthalten, natur ist sicher.": "Les yaourts aux fruits et les mélanges de muesli peuvent contenir du gluten, le nature est sûr.",
  "Kartoffeln mit Ei und Kraeuterjoghurt": "Pommes de terre, œufs et yaourt aux herbes",
  "Mild und satt. Schale weglassen macht es noch schonender fuer den Bauch.": "Doux et rassasiant. Les éplucher rend le plat encore plus doux pour le ventre.",
  "500 g Kartoffeln": "500 g de pommes de terre",
  "2 Eier": "2 œufs",
  "150 g Joghurt": "150 g de yaourt",
  "Schnittlauch oder Dill, Salz": "Ciboulette ou aneth, sel",
  "Kartoffeln 20 Minuten kochen, Eier die letzten 9 Minuten mitkochen.": "Cuire les pommes de terre 20 minutes, ajouter les œufs pour les 9 dernières.",
  "Joghurt mit Kraeutern und Salz verruehren.": "Mélanger le yaourt avec les herbes et le sel.",
  "Alles zusammen auf den Teller.": "Tout ensemble dans l'assiette.",
  "Kocht man die doppelte Menge Kartoffeln, ist morgen schon etwas da.": "En cuisant deux fois plus de pommes de terre, il y a déjà quelque chose de prêt demain.",
  "Huehnersuppe mit Reis und Karotte": "Soupe de poulet au riz et à la carotte",
  "Die Suppe fuer Infekte und schlechte Bauchtage. Friert gut ein.": "La soupe des infections et des mauvais jours pour le ventre. Se congèle bien.",
  "2 Huehnerbrustfilets oder -keulen": "2 blancs ou cuisses de poulet",
  "2 Karotten, 1 Stueck Sellerie": "2 carottes, 1 morceau de céleri-rave",
  "80 g Reis": "80 g de riz",
  "1,2 l Wasser, Salz, Lorbeer": "1,2 l d'eau, sel, laurier",
  "Huhn mit Gemuese und Lorbeer im Wasser 20 Minuten leise koecheln.": "Faire frémir le poulet avec les légumes et le laurier dans l'eau pendant 20 minutes.",
  "Huhn herausnehmen, zerzupfen, Reis in die Bruehe, 12 Minuten.": "Retirer le poulet, l'effilocher, mettre le riz dans le bouillon, 12 minutes.",
  "Huhn zurueck, salzen.": "Remettre le poulet, assaisonner.",
  "Selbst gekocht ist die Bruehe sicher glutenfrei, Wuerfel und Pulver oft nicht.": "Un bouillon maison est sûrement sans gluten, les cubes et poudres souvent pas.",
  "Kichererbsen und Suesskartoffel vom Blech": "Pois chiches et patates douces au four",
  "Fuenf Minuten Arbeit, der Ofen macht den Rest. Reicht fuer drei Tage.": "Cinq minutes de travail, le four fait le reste. De quoi tenir trois jours.",
  "1 Dose Kichererbsen": "1 boîte de pois chiches",
  "2 Suesskartoffeln": "2 patates douces",
  "1 rote Zwiebel": "1 oignon rouge",
  "Olivenoel, Paprikapulver, Kreuzkuemmel, Salz": "Huile d'olive, paprika, cumin, sel",
  "Tahin oder Joghurt zum Darueber": "Tahini ou yaourt pour napper",
  "Ofen auf 210 Grad.": "Four à 210 °C.",
  "Alles grob schneiden, mit Oel und Gewuerzen aufs Blech.": "Tout couper grossièrement, sur la plaque avec l'huile et les épices.",
  "25 Minuten, einmal wenden.": "25 minutes, retourner une fois.",
  "Gewuerzmischungen koennen Weizenmehl als Rieselhilfe enthalten, Einzelgewuerze sind sicherer.": "Les mélanges d'épices peuvent contenir de la farine de blé comme anti-agglomérant, les épices seules sont plus sûres.",
  "Raeucherforelle mit Kartoffeln und Gurke": "Truite fumée, pommes de terre et concombre",
  "Regional, fertig geraeuchert, mild. Omega-3 ohne Pfanne.": "Locale, déjà fumée, douce. Des oméga-3 sans poêle.",
  "1 Raeucherforellenfilet": "1 filet de truite fumée",
  "400 g Kartoffeln": "400 g de pommes de terre",
  "1/2 Gurke": "1/2 concombre",
  "Zitrone, Dill, Olivenoel": "Citron, aneth, huile d'olive",
  "Kartoffeln kochen.": "Cuire les pommes de terre.",
  "Gurke in Scheiben, mit Zitrone und Dill.": "Concombre en rondelles, avec citron et aneth.",
  "Forelle zerpfluecken und dazu.": "Émietter la truite à côté.",
  "Kren aus dem Glas kann Weizen enthalten, frisch gerieben ist sicher.": "Le raifort en bocal peut contenir du blé, le raifort râpé frais est sûr.",
  "Buchweizenbrei mit Apfel und Zimt": "Bouillie de sarrasin à la pomme et à la cannelle",
  "Buchweizen ist trotz des Namens kein Weizen. Warm, nussig, mit Eisen und Ballaststoffen.": "Malgré son autre nom, blé noir, le sarrasin n'est pas du blé. Chaud, au goût de noisette, avec du fer et des fibres.",
  "50 g Buchweizenflocken (glutenfrei gekennzeichnet)": "50 g de flocons de sarrasin (étiquetés sans gluten)",
  "200 ml Milch oder Pflanzendrink": "200 ml de lait ou de boisson végétale",
  "1 Apfel gerieben": "1 pomme râpée",
  "Zimt, 1 TL Nussmus": "Cannelle, 1 c. à café de purée d'oléagineux",
  "Flocken mit Milch 5 Minuten koecheln.": "Faire mijoter les flocons dans le lait 5 minutes.",
  "Apfel und Zimt einruehren.": "Incorporer la pomme et la cannelle.",
  "Nussmus darauf.": "Purée d'oléagineux par-dessus.",
  "Auch bei Buchweizen auf das Glutenfrei-Zeichen achten, wegen Verunreinigung in der Muehle.": "Vérifie aussi le logo sans gluten sur le sarrasin, à cause des contaminations au moulin.",
  "Omelett mit Zucchini und Feta": "Omelette courgette et feta",
  "Zehn Minuten, eine Pfanne, viel Eiweiss. Geht auch zum Abendessen.": "Dix minutes, une poêle, beaucoup de protéines. Ça marche aussi le soir.",
  "3 Eier": "3 œufs",
  "1/2 Zucchini, fein gerieben": "1/2 courgette finement râpée",
  "30 g Feta": "30 g de feta",
  "Olivenoel, Pfeffer": "Huile d'olive, poivre",
  "Zucchini in Oel 2 Minuten anbraten.": "Faire revenir la courgette dans l'huile 2 minutes.",
  "Verquirlte Eier darueber, bei kleiner Hitze stocken lassen.": "Verser les œufs battus par-dessus, laisser prendre à feu doux.",
  "Feta darueber, zuklappen.": "Feta par-dessus, replier.",
  "Mit Reiswaffeln oder Kartoffeln vom Vortag ist es eine ganze Mahlzeit.": "Avec des galettes de riz ou des pommes de terre de la veille, c'est un repas complet.",
  "Weisse Bohnen in Tomate mit Rosmarin": "Haricots blancs à la tomate et au romarin",
  "Zwei Dosen und ein Zweig Rosmarin. Mediterran, eisenreich und billig.": "Deux boîtes et un brin de romarin. Méditerranéen, riche en fer et bon marché.",
  "1 Dose weisse Bohnen": "1 boîte de haricots blancs",
  "1 Dose gehackte Tomaten": "1 boîte de tomates concassées",
  "1 Knoblauchzehe, 1 Zweig Rosmarin": "1 gousse d'ail, 1 brin de romarin",
  "Olivenoel, Salz, Pfeffer": "Huile d'olive, sel, poivre",
  "Knoblauch und Rosmarin in Oel kurz anschwitzen.": "Faire suer brièvement l'ail et le romarin dans l'huile.",
  "Tomaten und abgespuelte Bohnen dazu, 10 Minuten koecheln.": "Ajouter les tomates et les haricots rincés, laisser mijoter 10 minutes.",
  "Mit Oel und Pfeffer fertig.": "Terminer avec l'huile et le poivre.",
  "Dazu glutenfreies Brot oder Polenta. Bei empfindlichem Bauch die Menge klein halten.": "Servir avec du pain sans gluten ou de la polenta. Avec un ventre sensible, garder une petite portion.",
  "Mehrmals Gluten in zwei Wochen. Versteckte Quellen suchen: Sojasauce, Bruehen, Hafer, gemeinsamer Toaster. Halten Beschwerden trotz Diaet an, gehoert das zum Termin.": "Du gluten plusieurs fois en deux semaines. Chercher les sources cachées : sauce soja, bouillons, avoine, grille-pain partagé. Si les symptômes persistent malgré le régime, c'est à aborder au rendez-vous.",
  "Kann eine Entzuendung von Rippenfell oder Herzbeutel sein. Zeitnah aerztlich abklaeren lassen, bei Atemnot sofort.": "Peut être une inflammation de la plèvre ou du péricarde. Faire vérifier rapidement par un médecin, immédiatement en cas d'essoufflement.",
  "Kann Eiweiss im Urin bedeuten, ein fruehes Zeichen einer Nierenbeteiligung. Urin untersuchen lassen.": "Peut signifier des protéines dans les urines, un signe précoce d'atteinte rénale. Faire analyser les urines.",
  "Wassereinlagerungen koennen mit der Niere zusammenhaengen. Ansprechen und den Urin pruefen lassen.": "Une rétention d'eau peut être liée aux reins. En parler et faire contrôler les urines.",
  "Lunge, Herz oder Blutarmut koennen dahinterstecken. Zeitnah abklaeren, bei Atemnot in Ruhe sofort.": "Les poumons, le cœur ou une anémie peuvent en être la cause. Faire vérifier rapidement, immédiatement en cas d'essoufflement au repos.",
  "Kann ein Schub oder ein Infekt sein, unter Immunsuppression zaehlt beides. Mit der Praxis klaeren.": "Peut être une poussée ou une infection, et sous immunosuppression les deux comptent. Voir avec le cabinet.",
  "Oft viel Sonne abbekommen. UV-Licht kann Haut- und Allgemeinschuebe ausloesen, Schutz lohnt sich jeden Tag.": "Souvent beaucoup de soleil. Les UV peuvent déclencher des poussées cutanées et générales, se protéger vaut la peine chaque jour.",
  "Alfalfa-Sprossen: bei Lupus besser weglassen.": "Graines germées de luzerne : à éviter en cas de lupus.",
  "Ein ganz geschwollener Finger oder Zeh ist typisch fuer eine Psoriasis-Arthritis. Frueh in der Dermatologie oder Rheumatologie ansprechen.": "Un doigt ou un orteil entièrement gonflé est typique du rhumatisme psoriasique. En parler tôt en dermatologie ou en rhumatologie.",
  "Halsentzuendungen durch Streptokokken koennen einen Psoriasis-Schub ausloesen, unter systemischer Behandlung zaehlt jeder Infekt. Der Praxis sagen.": "Les angines à streptocoques peuvent déclencher une poussée de psoriasis, et sous traitement systémique chaque infection compte. Le signaler au cabinet.",
  "Enthaelt Alkohol. Bei Psoriasis und unter Methotrexat zurueckhaltend, beim Kochen verfliegt nicht alles.": "Contient de l'alcool. Avec un psoriasis et sous méthotrexate, avec modération : la cuisson ne l'élimine pas entièrement.",
  "Kann bedeuten, dass die Dosis zu hoch ist. TSH kontrollieren lassen.": "Peut signifier que la dose est trop élevée. Faire contrôler la TSH.",
  "Die Tablette oefter vergessen oder mit Essen genommen. Das verschiebt den TSH-Wert; vor der naechsten Kontrolle ansprechen.": "Le comprimé a souvent été oublié ou pris en mangeant. Cela décale la TSH ; en parler avant le prochain contrôle.",
  "Soja: nicht kurz nach der Schilddruesentablette essen, sonst wird weniger Hormon aufgenommen.": "Soja : ne pas en manger peu après le comprimé pour la thyroïde, sinon moins d'hormone est absorbée.",
  "Unter Basistherapie und Biologika koennen Infekte schwerer verlaufen. Die Praxis fragen, ob an den Medikamenten etwas zu aendern ist.": "Sous traitement de fond et biothérapies, les infections peuvent être plus sévères. Demander au cabinet s'il faut modifier quelque chose aux médicaments.",
  "An mehreren Tagen ueber eine Stunde steif am Morgen. Das spricht fuer aktive Entzuendung und gehoert vor den naechsten Routinetermin.": "Raideur matinale de plus d'une heure plusieurs jours. Cela évoque une inflammation active et doit être signalé avant le prochain rendez-vous de routine.",
  "Enthaelt Alkohol. Unter Methotrexat zurueckhaltend, beim Kochen verfliegt nicht alles.": "Contient de l'alcool. Sous méthotrexate, avec modération : la cuisson ne l'élimine pas entièrement.",
  "Kann einen Schub anzeigen. Der Praxis melden, mit Fieber oder vielen Stuhlgaengen noch am selben Tag.": "Peut annoncer une poussée. Le signaler au cabinet, le jour même en cas de fièvre ou de selles nombreuses.",
  "Bei CED kann Fieber Schub, Abszess oder Infekt bedeuten, unter Immunsuppression zaehlt alles davon. Mit der Praxis klaeren.": "Dans les MICI, la fièvre peut signifier poussée, abcès ou infection, et sous immunosuppression tout cela compte. Voir avec le cabinet.",
  "Stuhlgang in der Nacht spricht eher fuer Entzuendung als fuer einen gereizten Darm. Beim Termin ansprechen.": "Aller à la selle la nuit évoque plutôt une inflammation qu'un intestin irritable. En parler au rendez-vous.",
  "An mehreren Tagen sieben oder mehr Stuhlgaenge. Das kann ein Schub sein; der Praxis melden.": "Sept selles ou plus plusieurs jours. Cela peut être une poussée ; le signaler au cabinet."
 },
 "es": {
  "Zoeliakie": "Celiaquía",
  "Glutenfreie Ernaehrung ist die Behandlung. Die App fragt jeden Tag nach dem Essen und behaelt die Werte im Blick, die bei Zoeliakie kippen.": "La dieta sin gluten es el tratamiento. La app pregunta cada día por la comida y vigila los valores que suelen bajar en la celiaquía.",
  "Bauch": "Barriga",
  "ruhig": "tranquila",
  "starke Beschwerden": "molestias fuertes",
  "Der Tag beim Essen": "El día en la mesa",
  "Alles sicher": "Todo seguro",
  "Etwas war unsicher": "Algo no era seguro",
  "Gluten bekommen": "He tomado gluten",
  "Weizen, Roggen, Gerste, Dinkel und alles daraus": "Trigo, centeno, cebada, espelta y todo lo que se hace con ellos",
  "Schon kleine Mengen schaedigen die Duenndarmschleimhaut, auch ohne spuerbare Beschwerden.": "Incluso pequeñas cantidades dañan la mucosa del intestino delgado, con o sin síntomas.",
  "Hafer nur als glutenfrei gekennzeichnet": "Avena solo si está etiquetada sin gluten",
  "Normaler Hafer ist fast immer verunreinigt. Ein kleiner Teil der Betroffenen vertraegt auch reinen Hafer nicht; das zeigt der Verlauf, nicht ein Gefuehl.": "La avena normal casi siempre está contaminada. Una pequeña parte de las personas reacciona también a la avena pura; lo muestra la evolución, no una sensación.",
  "Sojasauce, Malz, Bruehen, Fertigsaucen": "Salsa de soja, malta, caldos, salsas preparadas",
  "Die haeufigsten versteckten Quellen. Das Zutatenverzeichnis jedes Mal lesen, Rezepturen aendern sich.": "Las fuentes ocultas más frecuentes. Lee los ingredientes cada vez, las recetas cambian.",
  "Eisen, Kalzium, Vitamin D, Folsaeure, B12 im Blick": "Hierro, calcio, vitamina D, ácido fólico, B12 bajo control",
  "Bei Zoeliakie oft niedrig, besonders am Anfang. Messen lassen statt auf Verdacht ergaenzen.": "A menudo bajos en la celiaquía, sobre todo al principio. Mejor medirlos que suplementar a ciegas.",
  "Brauche ich eine Ueberweisung zur Diaetologie?": "¿Necesito un volante para dietética?",
  "Systemischer Lupus (SLE)": "Lupus eritematoso sistémico (LES)",
  "Lupus": "Lupus",
  "Lupus zeigt sich ueberall ein wenig. Die App sammelt Gelenke, Haut, Kopf und Muedigkeit an einer Stelle, damit beim Termin das Muster sichtbar wird.": "El lupus aparece un poco por todas partes. La app reúne articulaciones, piel, cabeza y cansancio en un solo sitio, para que en la consulta se vea el patrón.",
  "Gelenke": "Articulaciones",
  "frei": "libres",
  "steif, geschwollen": "rígidas, hinchadas",
  "Kopf klar": "Cabeza despejada",
  "klar": "despejada",
  "im Nebel": "con niebla",
  "Sonne und Licht": "Sol y luz",
  "Geschuetzt": "Con protección",
  "Etwas abbekommen": "Algo de sol",
  "Viel abbekommen": "Mucho sol",
  "Mediterranes Muster": "Un patrón mediterráneo",
  "Gemuese, Huelsenfruechte, Olivenoel, Fisch. Es gibt Hinweise auf weniger Krankheitsaktivitaet und ein besseres Herzrisiko, aber keine Diaet, die Lupus heilt.": "Verduras, legumbres, aceite de oliva, pescado. Hay indicios de menor actividad de la enfermedad y mejor riesgo cardiaco, pero ninguna dieta cura el lupus.",
  "Alfalfa-Sprossen": "Brotes de alfalfa",
  "Enthalten L-Canavanin, das in Berichten Lupus-aehnliche Schuebe ausgeloest hat. Die Belege sind alt und duenn, der Verzicht kostet nichts.": "Contienen L-canavanina, que en casos descritos ha desencadenado brotes parecidos al lupus. Las pruebas son antiguas y escasas; renunciar a ellos no cuesta nada.",
  "Echinacea und andere Immun-Booster": "Equinácea y otros estimulantes inmunitarios",
  "Sollen das Immunsystem anregen, genau das ist bei Lupus nicht das Ziel. Vorher in der Sprechstunde fragen.": "Sirven para estimular el sistema inmunitario, que en el lupus no es el objetivo. Pregunta antes en la consulta.",
  "Kalzium und Vitamin D bei Kortison": "Calcio y vitamina D con corticoides",
  "Kortison kostet Knochen. Ob und wie viel ergaenzt wird, entscheidet die Aerztin nach Messung.": "Los corticoides debilitan los huesos. Si hay que suplementar y cuánto lo decide el médico tras medirlo.",
  "Wie aktiv ist mein Lupus gerade, in Zahlen?": "¿Qué actividad tiene mi lupus ahora mismo, en números?",
  "Wann wurde zuletzt der Urin auf Eiweiss geprueft?": "¿Cuándo se revisó por última vez la proteína en la orina?",
  "Wann ist die naechste Netzhautkontrolle faellig?": "¿Cuándo toca la próxima revisión de la retina?",
  "Psoriasis": "Psoriasis",
  "Haut, Juckreiz und Gelenke. Gelenkbeschwerden bei Psoriasis gehoeren frueh angesprochen, weil eine Psoriasis-Arthritis behandelbar ist, bevor sie Schaden macht.": "Piel, picor y articulaciones. Las molestias articulares con psoriasis deben comentarse pronto, porque la artritis psoriásica se puede tratar antes de que cause daños.",
  "Haut": "Piel",
  "stark befallen": "muy extensa",
  "Juckreiz": "Picor",
  "keiner": "ninguno",
  "quaelend": "insoportable",
  "Haut gepflegt und behandelt": "Piel cuidada y tratada",
  "Wie geplant": "Como estaba previsto",
  "Teilweise": "En parte",
  "Heute nicht": "Hoy no",
  "neue Plaques": "placas nuevas",
  "Kopfhaut": "cuero cabelludo",
  "Naegel": "uñas",
  "Hautrisse": "piel agrietada",
  "geschwollener Finger oder Zeh": "dedo de la mano o del pie hinchado",
  "Infekt, Halsweh": "infección, dolor de garganta",
  "Gewicht und mediterranes Muster": "Peso y patrón mediterráneo",
  "Bei Uebergewicht bessert Abnehmen die Haut in Studien messbar und laesst Medikamente besser wirken.": "Con sobrepeso, perder algunos kilos mejora la piel de forma medible en los estudios y ayuda a que el tratamiento funcione mejor.",
  "Alkohol": "Alcohol",
  "Haengt mit schwereren Verlaeufen zusammen und vertraegt sich mit einigen Medikamenten schlecht, etwa Methotrexat.": "Se asocia a formas más graves y no combina bien con algunos fármacos, como el metotrexato.",
  "Glutenfrei nur mit Grund": "Sin gluten solo con motivo",
  "Hilft in Studien nur, wenn Zoeliakie-Antikoerper nachweisbar sind. Dann aber deutlich. Testen lassen statt raten.": "En los estudios solo ayuda si hay anticuerpos de celiaquía. Entonces ayuda claramente. Hazte la prueba, no adivines.",
  "Koennten meine Gelenkbeschwerden eine Psoriasis-Arthritis sein?": "¿Podrían mis molestias articulares ser una artritis psoriásica?",
  "Wie gross ist der befallene Hautanteil, und ist eine systemische Behandlung sinnvoll?": "¿Qué superficie de piel está afectada y tendría sentido un tratamiento sistémico?",
  "Sollen Blutdruck, Blutfette und Blutzucker kontrolliert werden?": "¿Hay que controlar la tensión, los lípidos y el azúcar en sangre?",
  "Hashimoto-Thyreoiditis": "Tiroiditis de Hashimoto",
  "Hashimoto": "Hashimoto",
  "Viel haengt an einer Tablette zur richtigen Zeit und an einem Wert. Die App fragt nach dem einen und behaelt den anderen im Verlauf.": "Mucho depende de un comprimido a la hora adecuada y de un valor. La app pregunta por lo primero y sigue lo segundo en el tiempo.",
  "Kaelteempfinden": "Sensación de frío",
  "normal": "normal",
  "staendig kalt": "frío constante",
  "Schilddruesentablette": "Comprimido para el tiroides",
  "Nuechtern genommen": "Tomado en ayunas",
  "Mit Essen oder Kaffee": "Con comida o café",
  "Vergessen": "Olvidado",
  "kaelteempfindlich": "sensibilidad al frío",
  "Gewicht steigt": "peso en aumento",
  "trockene Haut": "piel seca",
  "Stimmung gedrueckt": "ánimo bajo",
  "fT4": "T4 libre",
  "Schilddruese": "Tiroides",
  "Das freie Schilddruesenhormon. Zusammen mit dem TSH sagt es, ob die Dosis passt. Blut am besten vor der Tabletteneinnahme abnehmen lassen.": "La hormona tiroidea libre. Junto con la TSH indica si la dosis es adecuada. Mejor sacarse sangre antes del comprimido.",
  "TPO-Antikoerper": "Anticuerpos anti-TPO",
  "Bestaetigen die Autoimmunerkrankung. Ihre Hoehe steuert nicht die Behandlung und muss nicht laufend gemessen werden.": "Confirman la enfermedad autoinmune. Su nivel no guía el tratamiento y no hace falta medirlos con regularidad.",
  "Tablette nuechtern, mit Wasser": "Comprimido en ayunas, con agua",
  "30 bis 60 Minuten vor dem Fruehstueck, immer gleich. Kaffee, Soja und Ballaststoffe dazwischen verringern die Aufnahme.": "De 30 a 60 minutos antes del desayuno, siempre igual. El café, la soja y la fibra en ese intervalo reducen la absorción.",
  "Kalzium, Eisen und Magnesium mit Abstand": "Calcio, hierro y magnesio separados",
  "Mindestens vier Stunden Abstand zur Tablette, sonst wird weniger Hormon aufgenommen.": "Al menos cuatro horas de separación del comprimido; si no, se absorbe menos hormona.",
  "Jod und Selen nicht auf eigene Faust": "Yodo y selenio no por tu cuenta",
  "Normale Ernaehrung mit Jodsalz reicht. Hoch dosierte Praeparate koennen schaden, der Nutzen von Selen ist nicht gesichert.": "Una alimentación normal con sal yodada basta. Los productos de dosis alta pueden perjudicar; el beneficio del selenio no está demostrado.",
  "Passt meine Dosis zum letzten TSH-Wert, und wann wird wieder kontrolliert?": "¿Mi dosis encaja con la última TSH y cuándo es el próximo control?",
  "Muss ich den Abstand zu anderen Medikamenten oder Ergaenzungen aendern?": "¿Tengo que cambiar la separación con otros medicamentos o suplementos?",
  "Rheumatoide Arthritis": "Artritis reumatoide",
  "Arthritis": "Artritis",
  "Welche Gelenke, wie lange steif am Morgen, wie geschwollen. Genau das fragt die Rheumatologie, und genau das vergisst man bis zum Termin.": "Qué articulaciones, cuánto tiempo rígidas por la mañana, cuánto hinchadas. Es justo lo que pregunta reumatología, y justo lo que se olvida antes de la cita.",
  "Steif am Morgen": "Rigidez por la mañana",
  "Unter 30 Minuten": "Menos de 30 minutos",
  "30 bis 60 Minuten": "De 30 a 60 minutos",
  "Ueber eine Stunde": "Más de una hora",
  "geschwollene Gelenke": "articulaciones hinchadas",
  "Rheumafaktor": "Factor reumatoide",
  "Hilft bei der Diagnose. Fuer den Verlauf sagen CRP, BSG und die Gelenke mehr.": "Ayuda en el diagnóstico. Para la evolución dicen más la PCR, la VSG y las articulaciones.",
  "Anti-CCP": "Anti-CCP",
  "Sehr spezifisch fuer rheumatoide Arthritis. Wird meist einmal bestimmt, nicht laufend.": "Muy específicos de la artritis reumatoide. Normalmente se miden una vez, no repetidamente.",
  "ALT (GPT)": "ALT (GPT)",
  "Leber": "Hígado",
  "Leberwert. Wird unter Methotrexat und einigen anderen Medikamenten regelmaessig kontrolliert.": "Valor hepático. Se controla con regularidad con metotrexato y algunos otros fármacos.",
  "Mediterran, mit Fisch": "Mediterránea, con pescado",
  "Omega-3-Fettsaeuren lindern Gelenkbeschwerden in Studien leicht. Sie ersetzen keine Basistherapie.": "Los ácidos grasos omega-3 alivian ligeramente las molestias articulares en los estudios. No sustituyen el tratamiento de fondo.",
  "Alkohol unter Methotrexat": "Alcohol con metotrexato",
  "Belastet zusammen die Leber. Wie viel vertretbar ist, in der Sprechstunde klaeren.": "Juntos sobrecargan el hígado. Cuánto es aceptable es una pregunta para la consulta.",
  "Nicht rauchen": "No fumar",
  "Rauchen verschlechtert den Verlauf und das Ansprechen auf Medikamente deutlich.": "Fumar empeora claramente la evolución y la respuesta a los medicamentos.",
  "Ist das Ziel Remission erreicht, und wenn nicht, was ist der naechste Schritt?": "¿Se ha alcanzado el objetivo de remisión y, si no, cuál es el siguiente paso?",
  "Welche Kontrollen brauche ich unter meiner Basistherapie, und wie oft?": "¿Qué controles necesito con mi tratamiento de fondo y con qué frecuencia?",
  "Morbus Crohn oder Colitis ulcerosa": "Enfermedad de Crohn o colitis ulcerosa",
  "CED": "EII",
  "Bauch, Stuhl und Blut darin. Unangenehm aufzuschreiben, und gerade deshalb wertvoll: genau diese Zahlen entscheiden ueber die Behandlung.": "Barriga, heces y sangre en ellas. Desagradable de apuntar y valioso justo por eso: estos números deciden el tratamiento.",
  "Stuhlgaenge heute": "Deposiciones hoy",
  "0 bis 3": "De 0 a 3",
  "4 bis 6": "De 4 a 6",
  "7 oder mehr": "7 o más",
  "Blut im Stuhl": "sangre en las heces",
  "naechtlicher Stuhlgang": "deposición nocturna",
  "Calprotectin im Stuhl": "Calprotectina fecal",
  "Darm": "Intestino",
  "Zeigt Entzuendung im Darm, ohne Spiegelung. Steigt oft, bevor Beschwerden kommen.": "Muestra la inflamación intestinal sin endoscopia. A menudo sube antes que los síntomas.",
  "Persoenliche Vertraeglichkeit zaehlt": "Cuenta la tolerancia personal",
  "Es gibt keine Diaet fuer alle. Ein Ernaehrungstagebuch ist ehrlicher als jede Liste.": "No hay una dieta para todo el mundo. Un diario de comidas es más honesto que cualquier lista.",
  "Im Schub: schonend und ballaststoffarm nur nach Ruecksprache": "En un brote: suave y baja en fibra solo con consejo",
  "Bei Engstellen kann es noetig sein, sonst sind Ballaststoffe eher hilfreich. Das entscheidet die Gastroenterologie.": "Con estenosis puede ser necesario; si no, la fibra suele ayudar. Lo decide gastroenterología.",
  "Eisen, B12, Vitamin D messen lassen": "Medir hierro, B12 y vitamina D",
  "Blutverlust und Entzuendung zehren daran, besonders bei Befall des Duenndarms.": "La pérdida de sangre y la inflamación los agotan, sobre todo si está afectado el intestino delgado.",
  "Wie ist mein Calprotectin im Verlauf, und wann wird wieder gespiegelt?": "¿Cómo evoluciona mi calprotectina y cuándo es la próxima endoscopia?",
  "Was tue ich bei Blut im Stuhl oder Fieber, und wen rufe ich an?": "¿Qué hago si hay sangre en las heces o fiebre, y a quién llamo?",
  "Wie geht es dir": "Cómo estás",
  "sehr schlecht": "muy mal",
  "sehr gut": "muy bien",
  "Muedigkeit": "Cansancio",
  "wach": "con energía",
  "erschoepft": "agotamiento total",
  "Schmerz": "Dolor",
  "stark": "fuerte",
  "Weiche Polenta mit Ei und Spinat": "Polenta cremosa con huevo y espinacas",
  "Warm, weich, in einem Topf. Gut an Tagen, an denen der Bauch empfindlich ist.": "Caliente, suave, en una sola olla. Buena para los días en que la barriga está sensible.",
  "60 g Instant-Polenta (Maisgriess, glutenfrei gekennzeichnet)": "60 g de polenta instantánea (sémola de maíz etiquetada sin gluten)",
  "250 ml Wasser oder glutenfreie Bruehe": "250 ml de agua o caldo sin gluten",
  "1 Ei": "1 huevo",
  "1 Handvoll Babyspinat": "1 puñado de espinacas baby",
  "1 EL Parmesan, etwas Olivenoel": "1 cucharada de parmesano, un chorrito de aceite de oliva",
  "Wasser aufkochen, Polenta einruehren, 5 Minuten leise ruehren.": "Llevar el agua a ebullición, añadir la polenta y remover suavemente 5 minutos.",
  "Mulde druecken, Ei hineinschlagen, Deckel drauf, 4 Minuten.": "Hacer un hueco, cascar el huevo dentro, tapar, 4 minutos.",
  "Spinat und Parmesan darueber, Oel dazu.": "Espinacas y parmesano por encima, añadir el aceite.",
  "Maisgriess ist von Natur aus glutenfrei, wird aber oft in Muehlen mit Weizen verarbeitet. Auf das Zeichen achten.": "La sémola de maíz no tiene gluten de forma natural, pero a menudo se muele junto al trigo. Busca el símbolo.",
  "Reis mit Sardinen, Zitrone und Petersilie": "Arroz con sardinas, limón y perejil",
  "Aus dem Vorrat, mit Kalzium aus den Graeten und Omega-3. Fertigreis macht es zu zehn Minuten.": "De la despensa, con el calcio de las espinas y omega-3. Con arroz precocido son diez minutos.",
  "1 Beutel vorgegarter Reis (Zutaten pruefen)": "1 bolsa de arroz precocido (revisar ingredientes)",
  "1 Dose Sardinen in Olivenoel": "1 lata de sardinas en aceite de oliva",
  "1/2 Zitrone": "1/2 limón",
  "Petersilie, Pfeffer": "Perejil, pimienta",
  "Reis erwaermen.": "Calentar el arroz.",
  "Sardinen mit dem Oel darueber, grob zerdruecken.": "Las sardinas con su aceite por encima, desmigarlas en trozos.",
  "Zitrone, Petersilie, Pfeffer.": "Limón, perejil, pimienta.",
  "Gewuerzter Fertigreis kann Gluten enthalten, natur ist sicher.": "El arroz preparado con condimentos puede llevar gluten; el natural es seguro.",
  "Linsensalat mit Paprika und Zitrone": "Ensalada de lentejas con pimiento y limón",
  "Eisen aus den Linsen, Vitamin C aus Paprika und Zitrone hilft bei der Aufnahme.": "Hierro de las lentejas, y la vitamina C del pimiento y el limón ayuda a absorberlo.",
  "1 Glas oder Dose gekochte Linsen": "1 bote o lata de lentejas cocidas",
  "1 rote Paprika": "1 pimiento rojo",
  "1/2 rote Zwiebel": "1/2 cebolla morada",
  "Saft einer Zitrone, 2 EL Olivenoel": "El zumo de un limón, 2 cucharadas de aceite de oliva",
  "Petersilie, Salz": "Perejil, sal",
  "Linsen abspuelen.": "Enjuagar las lentejas.",
  "Paprika und Zwiebel klein schneiden.": "Picar el pimiento y la cebolla.",
  "Alles mischen, haelt zwei Tage im Kuehlschrank.": "Mezclarlo todo; aguanta dos días en la nevera.",
  "Kaffee und schwarzer Tee zum Essen mindern die Eisenaufnahme, lieber eine Stunde Abstand.": "El café y el té negro con la comida reducen la absorción del hierro; mejor con una hora de separación.",
  "Lachs mit Quinoa und Brokkoli": "Salmón con quinoa y brócoli",
  "Ein Topf, eine Pfanne, zwanzig Minuten. Omega-3 und Eiweiss fuer zwei Mahlzeiten.": "Una olla, una sartén, veinte minutos. Omega-3 y proteína para dos comidas.",
  "120 g Quinoa": "120 g de quinoa",
  "2 Lachsfilets": "2 lomos de salmón",
  "1 Brokkoli": "1 brócoli",
  "Olivenoel, Zitrone, Salz": "Aceite de oliva, limón, sal",
  "Quinoa gut spuelen, mit doppelter Menge Wasser 15 Minuten koecheln.": "Enjuagar bien la quinoa y cocerla a fuego lento 15 minutos en el doble de agua.",
  "Brokkoli die letzten 5 Minuten oben drauf daempfen.": "Cocer el brócoli al vapor encima los últimos 5 minutos.",
  "Lachs in der Pfanne je Seite 3 bis 4 Minuten, Zitrone darueber.": "Salmón a la sartén 3-4 minutos por lado, limón por encima.",
  "Quinoa ist glutenfrei, Spuelen nimmt die bitteren Saponine.": "La quinoa no tiene gluten; enjuagarla elimina las saponinas amargas.",
  "Joghurtschale mit Nuessen und Beeren": "Bol de yogur con frutos secos y frutos rojos",
  "Kalzium und Eiweiss ohne Herd. Fuer den Morgen nach einer schlechten Nacht.": "Calcio y proteína sin cocinar. Para la mañana después de una mala noche.",
  "200 g Naturjoghurt oder Skyr": "200 g de yogur natural o skyr",
  "1 Handvoll Beeren, auch tiefgekuehlt": "1 puñado de frutos rojos, también congelados",
  "1 EL Walnuesse oder Mandeln": "1 cucharada de nueces o almendras",
  "1 TL Leinsamen geschrotet": "1 cucharadita de linaza molida",
  "Alles in eine Schale, fertig.": "Todo en un bol, listo.",
  "Fruchtjoghurt und Muesli-Mischungen koennen Gluten enthalten, natur ist sicher.": "Los yogures de frutas y las mezclas de muesli pueden llevar gluten; lo natural es seguro.",
  "Kartoffeln mit Ei und Kraeuterjoghurt": "Patatas con huevo y yogur de hierbas",
  "Mild und satt. Schale weglassen macht es noch schonender fuer den Bauch.": "Suave y saciante. Pelarlas lo hace aún más suave para la barriga.",
  "500 g Kartoffeln": "500 g de patatas",
  "2 Eier": "2 huevos",
  "150 g Joghurt": "150 g de yogur",
  "Schnittlauch oder Dill, Salz": "Cebollino o eneldo, sal",
  "Kartoffeln 20 Minuten kochen, Eier die letzten 9 Minuten mitkochen.": "Cocer las patatas 20 minutos; añadir los huevos los últimos 9.",
  "Joghurt mit Kraeutern und Salz verruehren.": "Mezclar el yogur con las hierbas y la sal.",
  "Alles zusammen auf den Teller.": "Todo junto en el plato.",
  "Kocht man die doppelte Menge Kartoffeln, ist morgen schon etwas da.": "Si cueces el doble de patatas, mañana ya tienes algo listo.",
  "Huehnersuppe mit Reis und Karotte": "Sopa de pollo con arroz y zanahoria",
  "Die Suppe fuer Infekte und schlechte Bauchtage. Friert gut ein.": "La sopa para las infecciones y los días malos de barriga. Se congela bien.",
  "2 Huehnerbrustfilets oder -keulen": "2 pechugas o muslos de pollo",
  "2 Karotten, 1 Stueck Sellerie": "2 zanahorias, 1 trozo de apionabo",
  "80 g Reis": "80 g de arroz",
  "1,2 l Wasser, Salz, Lorbeer": "1,2 l de agua, sal, laurel",
  "Huhn mit Gemuese und Lorbeer im Wasser 20 Minuten leise koecheln.": "Cocer a fuego lento el pollo con las verduras y el laurel en el agua durante 20 minutos.",
  "Huhn herausnehmen, zerzupfen, Reis in die Bruehe, 12 Minuten.": "Sacar el pollo, desmenuzarlo, echar el arroz al caldo, 12 minutos.",
  "Huhn zurueck, salzen.": "Volver a poner el pollo, sazonar.",
  "Selbst gekocht ist die Bruehe sicher glutenfrei, Wuerfel und Pulver oft nicht.": "El caldo casero es seguro sin gluten; las pastillas y los polvos a menudo no.",
  "Kichererbsen und Suesskartoffel vom Blech": "Garbanzos y boniato al horno",
  "Fuenf Minuten Arbeit, der Ofen macht den Rest. Reicht fuer drei Tage.": "Cinco minutos de trabajo, el horno hace el resto. Da para tres días.",
  "1 Dose Kichererbsen": "1 lata de garbanzos",
  "2 Suesskartoffeln": "2 boniatos",
  "1 rote Zwiebel": "1 cebolla morada",
  "Olivenoel, Paprikapulver, Kreuzkuemmel, Salz": "Aceite de oliva, pimentón, comino, sal",
  "Tahin oder Joghurt zum Darueber": "Tahini o yogur para aliñar",
  "Ofen auf 210 Grad.": "Horno a 210 °C.",
  "Alles grob schneiden, mit Oel und Gewuerzen aufs Blech.": "Cortarlo todo en trozos grandes, a la bandeja con aceite y especias.",
  "25 Minuten, einmal wenden.": "25 minutos, dar la vuelta una vez.",
  "Gewuerzmischungen koennen Weizenmehl als Rieselhilfe enthalten, Einzelgewuerze sind sicherer.": "Las mezclas de especias pueden llevar harina de trigo como antiapelmazante; las especias sueltas son más seguras.",
  "Raeucherforelle mit Kartoffeln und Gurke": "Trucha ahumada con patatas y pepino",
  "Regional, fertig geraeuchert, mild. Omega-3 ohne Pfanne.": "Local, ya ahumada, suave. Omega-3 sin sartén.",
  "1 Raeucherforellenfilet": "1 filete de trucha ahumada",
  "400 g Kartoffeln": "400 g de patatas",
  "1/2 Gurke": "1/2 pepino",
  "Zitrone, Dill, Olivenoel": "Limón, eneldo, aceite de oliva",
  "Kartoffeln kochen.": "Cocer las patatas.",
  "Gurke in Scheiben, mit Zitrone und Dill.": "Pepino en rodajas, con limón y eneldo.",
  "Forelle zerpfluecken und dazu.": "Desmigar la trucha al lado.",
  "Kren aus dem Glas kann Weizen enthalten, frisch gerieben ist sicher.": "El rábano picante en bote puede llevar trigo; el rallado fresco es seguro.",
  "Buchweizenbrei mit Apfel und Zimt": "Gachas de trigo sarraceno con manzana y canela",
  "Buchweizen ist trotz des Namens kein Weizen. Warm, nussig, mit Eisen und Ballaststoffen.": "A pesar del nombre, el trigo sarraceno no es trigo. Caliente, con sabor a fruto seco, con hierro y fibra.",
  "50 g Buchweizenflocken (glutenfrei gekennzeichnet)": "50 g de copos de trigo sarraceno (etiquetados sin gluten)",
  "200 ml Milch oder Pflanzendrink": "200 ml de leche o bebida vegetal",
  "1 Apfel gerieben": "1 manzana rallada",
  "Zimt, 1 TL Nussmus": "Canela, 1 cucharadita de crema de frutos secos",
  "Flocken mit Milch 5 Minuten koecheln.": "Cocer los copos en la leche a fuego lento 5 minutos.",
  "Apfel und Zimt einruehren.": "Añadir la manzana y la canela.",
  "Nussmus darauf.": "Crema de frutos secos por encima.",
  "Auch bei Buchweizen auf das Glutenfrei-Zeichen achten, wegen Verunreinigung in der Muehle.": "Busca también el símbolo sin gluten en el trigo sarraceno, por la contaminación en el molino.",
  "Omelett mit Zucchini und Feta": "Tortilla de calabacín y feta",
  "Zehn Minuten, eine Pfanne, viel Eiweiss. Geht auch zum Abendessen.": "Diez minutos, una sartén, mucha proteína. Sirve también para cenar.",
  "3 Eier": "3 huevos",
  "1/2 Zucchini, fein gerieben": "1/2 calabacín rallado fino",
  "30 g Feta": "30 g de feta",
  "Olivenoel, Pfeffer": "Aceite de oliva, pimienta",
  "Zucchini in Oel 2 Minuten anbraten.": "Saltear el calabacín en aceite 2 minutos.",
  "Verquirlte Eier darueber, bei kleiner Hitze stocken lassen.": "Verter los huevos batidos por encima y dejar cuajar a fuego bajo.",
  "Feta darueber, zuklappen.": "Feta por encima, doblar.",
  "Mit Reiswaffeln oder Kartoffeln vom Vortag ist es eine ganze Mahlzeit.": "Con tortitas de arroz o patatas del día anterior es una comida completa.",
  "Weisse Bohnen in Tomate mit Rosmarin": "Alubias blancas con tomate y romero",
  "Zwei Dosen und ein Zweig Rosmarin. Mediterran, eisenreich und billig.": "Dos latas y una ramita de romero. Mediterráneo, rico en hierro y barato.",
  "1 Dose weisse Bohnen": "1 lata de alubias blancas",
  "1 Dose gehackte Tomaten": "1 lata de tomate troceado",
  "1 Knoblauchzehe, 1 Zweig Rosmarin": "1 diente de ajo, 1 ramita de romero",
  "Olivenoel, Salz, Pfeffer": "Aceite de oliva, sal, pimienta",
  "Knoblauch und Rosmarin in Oel kurz anschwitzen.": "Sofreír brevemente el ajo y el romero en el aceite.",
  "Tomaten und abgespuelte Bohnen dazu, 10 Minuten koecheln.": "Añadir el tomate y las alubias enjuagadas, cocer a fuego lento 10 minutos.",
  "Mit Oel und Pfeffer fertig.": "Terminar con aceite y pimienta.",
  "Dazu glutenfreies Brot oder Polenta. Bei empfindlichem Bauch die Menge klein halten.": "Acompañar con pan sin gluten o polenta. Con la barriga sensible, mejor una ración pequeña.",
  "Mehrmals Gluten in zwei Wochen. Versteckte Quellen suchen: Sojasauce, Bruehen, Hafer, gemeinsamer Toaster. Halten Beschwerden trotz Diaet an, gehoert das zum Termin.": "Gluten varias veces en dos semanas. Busca fuentes ocultas: salsa de soja, caldos, avena, tostadora compartida. Si las molestias siguen a pesar de la dieta, llévalo a la consulta.",
  "Kann eine Entzuendung von Rippenfell oder Herzbeutel sein. Zeitnah aerztlich abklaeren lassen, bei Atemnot sofort.": "Puede ser una inflamación de la pleura o del pericardio. Que lo valore un médico pronto, de inmediato si falta el aire.",
  "Kann Eiweiss im Urin bedeuten, ein fruehes Zeichen einer Nierenbeteiligung. Urin untersuchen lassen.": "Puede indicar proteínas en la orina, un signo precoz de afectación renal. Haz que analicen la orina.",
  "Wassereinlagerungen koennen mit der Niere zusammenhaengen. Ansprechen und den Urin pruefen lassen.": "La retención de líquidos puede estar relacionada con el riñón. Coméntalo y haz que revisen la orina.",
  "Lunge, Herz oder Blutarmut koennen dahinterstecken. Zeitnah abklaeren, bei Atemnot in Ruhe sofort.": "Pueden estar detrás los pulmones, el corazón o una anemia. Que lo valoren pronto, de inmediato si falta el aire en reposo.",
  "Kann ein Schub oder ein Infekt sein, unter Immunsuppression zaehlt beides. Mit der Praxis klaeren.": "Puede ser un brote o una infección, y con inmunosupresión cuentan ambos. Consúltalo con la consulta.",
  "Oft viel Sonne abbekommen. UV-Licht kann Haut- und Allgemeinschuebe ausloesen, Schutz lohnt sich jeden Tag.": "A menudo mucho sol. La luz UV puede desencadenar brotes cutáneos y generales, protegerse merece la pena cada día.",
  "Alfalfa-Sprossen: bei Lupus besser weglassen.": "Brotes de alfalfa: con lupus, mejor evitarlos.",
  "Ein ganz geschwollener Finger oder Zeh ist typisch fuer eine Psoriasis-Arthritis. Frueh in der Dermatologie oder Rheumatologie ansprechen.": "Un dedo de la mano o del pie entero hinchado es típico de la artritis psoriásica. Coméntalo pronto en dermatología o reumatología.",
  "Halsentzuendungen durch Streptokokken koennen einen Psoriasis-Schub ausloesen, unter systemischer Behandlung zaehlt jeder Infekt. Der Praxis sagen.": "Las faringitis por estreptococo pueden desencadenar un brote de psoriasis, y con tratamiento sistémico cuenta cada infección. Díselo a la consulta.",
  "Enthaelt Alkohol. Bei Psoriasis und unter Methotrexat zurueckhaltend, beim Kochen verfliegt nicht alles.": "Contiene alcohol. Con psoriasis y con metotrexato, con moderación: al cocinar no se evapora todo.",
  "Kann bedeuten, dass die Dosis zu hoch ist. TSH kontrollieren lassen.": "Puede significar que la dosis es demasiado alta. Haz que controlen la TSH.",
  "Die Tablette oefter vergessen oder mit Essen genommen. Das verschiebt den TSH-Wert; vor der naechsten Kontrolle ansprechen.": "La pastilla se olvidó o se tomó con comida a menudo. Eso altera la TSH; coméntalo antes del próximo control.",
  "Soja: nicht kurz nach der Schilddruesentablette essen, sonst wird weniger Hormon aufgenommen.": "Soja: no la comas poco después de la pastilla del tiroides, o se absorberá menos hormona.",
  "Unter Basistherapie und Biologika koennen Infekte schwerer verlaufen. Die Praxis fragen, ob an den Medikamenten etwas zu aendern ist.": "Con el tratamiento de fondo y los biológicos, las infecciones pueden ser más graves. Pregunta en la consulta si hay que cambiar algo en la medicación.",
  "An mehreren Tagen ueber eine Stunde steif am Morgen. Das spricht fuer aktive Entzuendung und gehoert vor den naechsten Routinetermin.": "Rigidez matutina de más de una hora varios días. Apunta a una inflamación activa y conviene comentarlo antes de la próxima revisión.",
  "Enthaelt Alkohol. Unter Methotrexat zurueckhaltend, beim Kochen verfliegt nicht alles.": "Contiene alcohol. Con metotrexato, con moderación: al cocinar no se evapora todo.",
  "Kann einen Schub anzeigen. Der Praxis melden, mit Fieber oder vielen Stuhlgaengen noch am selben Tag.": "Puede indicar un brote. Avisa a la consulta, el mismo día si hay fiebre o muchas deposiciones.",
  "Bei CED kann Fieber Schub, Abszess oder Infekt bedeuten, unter Immunsuppression zaehlt alles davon. Mit der Praxis klaeren.": "En la EII, la fiebre puede significar brote, absceso o infección, y con inmunosupresión todo cuenta. Consúltalo con la consulta.",
  "Stuhlgang in der Nacht spricht eher fuer Entzuendung als fuer einen gereizten Darm. Beim Termin ansprechen.": "Ir al baño por la noche apunta más a inflamación que a un intestino irritable. Coméntalo en la consulta.",
  "An mehreren Tagen sieben oder mehr Stuhlgaenge. Das kann ein Schub sein; der Praxis melden.": "Siete o más deposiciones varios días. Puede ser un brote; avisa a la consulta."
 }
};
